<script>
    var tablelisturl = '<?=_PANEL_ROOT_;?>/<?=$controller;?>/documentslist/<?=$id;?>';
</script>
<div class="m-portlet m-portlet--full-height m-portlet--tabs">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                        <i class="flaticon-share m--hide"></i>
                        <?=$this->lang->get("Documents");?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="tab-content">
            <div class="tab-pane active" id="m_user_profile_tab_1">
                <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
                    <div class="m-portlet__body">
                        <?php if($success):?>
                            <div class="form-group m-form__group row">
                                <div class="form-success">
                                    <?=$success;?>
                                </div>
                            </div>
                        <?php endif;?>
                        <div class="form-group m-form__group row">
                            <div class="col-12" style="font-size: 16px;">
                                <b><?=$this->lang->get("Title");?>:</b> <?=htmlspecialchars($docdata->title);?>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <div class="col-12" style="font-size: 16px;">
                                <b><?=$this->lang->get("Amount");?>:</b> <?=$this->lib->floatToDanish($docdata->amount,2);?> kr.
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <div class="col-12" style="font-size: 16px;">
                                <b><?=$this->lang->get("Date");?>:</b> <?=$this->lib->dateToDanish($this->mymongo->dateFormat($docdata->date, "Y-m-d"));?>
                            </div>
                        </div>
                        <?php if(count($documents) == 0):?>
                            <div class="form-group m-form__group row">
                                <div class="form-error">
                                    <?=$this->lang->get("NotFoundDocument", "Document not found");?>
                                </div>
                            </div>
                        <?php endif;?>
                        <?php foreach($documents as $key => $value):?>
                            <div class="form-group m-form__group row">
                                <div class="col-1" style="width: 20px;"><b><?=$key+1;?>)</b></div>
                                <div class="col-3">
                                    <?php if(in_array($value->type, array("jpeg", "jpg", "png", "gif"))): ?>
                                        <a target="_blank" href="/upload/<?=(string)$value->uuid;?>/<?=(string)$value->_id;?>/org.jpg">
                                            <img style="max-width: 100%;" src="/upload/<?=(string)$value->uuid;?>/<?=(string)$value->_id;?>/medium.jpg?<?=microtime(true);?>"/>
                                        </a>
                                    <?php else: ?>
                                        <a target="_blank" href="/upload/<?=(string)$value->uuid;?>/<?=(string)$value->_id;?>/<?=(string)htmlspecialchars($value->filename).'.'.$value->type;?>"><b><?=(string)htmlspecialchars($value->filename).'.'.$value->type;?></b></a>
                                    <?php endif;?>
                                </div>
                                <?php if(in_array($value->type, array("jpeg", "jpg", "png", "gif"))): ?>
                                    <a href="<?=_PANEL_ROOT_;?>/documents/edit?id=<?=$value->_id;?>">
                                       <B><?=$this->lang->get("Edit");?></B>
                                    </a>
                                <?php endif;?>
                                <!--
                                    <div class="col-2">
                                        <a href="?id=<?=$this->request->get("id");?>&delete=<?=(string)$value->_id;?>"><i class="la la-trash redcolor"></i></a>
                                    </div>
                                    -->
                            </div>
                        <?php endforeach;?>


                        <hr/>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Status");?></label>
                            <div class="col-5">
                                <?php if($this->auth->isPermitted($this->lang, "case_activities", "edit")):?>
                                    <select class="form-control m-input" name="status">
                                        <?php foreach($this->parameters->getList($this->lang, "activity_statuses") as $value):?>
                                            <option value="<?=(int)$value["id"];?>" <?=((int)$docdata->status == (int)$value["id"] ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                        <?php endforeach;?>
                                    </select>
                                <?php else:?>
                                    <div style="padding-top: 8px;"><?=htmlspecialchars($this->parameters->getList($this->lang, "activity_statuses")[(int)$docdata->status]["title"]);?></div>
                                <?php endif?>
                            </div>

                        </div>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Note");?></label>
                            <div class="col-8">
                                <?php if($this->auth->isPermitted($this->lang, "case_activities", "edit")):?>
                                    <textarea class="form-control" name="description"><?=$docdata->description;?></textarea>
                                <?php else:?>
                                    <div style="padding-top: 8px;"><?=$docdata->description;?></div>
                                <?php endif?>
                            </div>
                        </div>
                        <?php if($this->auth->isPermitted($this->lang, "case_activities", "edit")):?>
                        <div class="form-group m-form__group row">
                            <div class="col-2">
                            </div>
                            <div class="col-5">
                                <?php if($success):?>
                                    <a href="<?=_PANEL_ROOT_;?>/case/activities/<?=$id;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                                <?php else:?>
                                    <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                                <?php endif?>
                            </div>
                        </div>
                        <?php endif?>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

