<script>
    var tablelisturl = '<?=_PANEL_ROOT_;?>/<?=$controller;?>/evalreportslist/<?=$id;?>?<?=$urlTag;?>';
</script>
<div class="m-portlet m-portlet--full-height m-portlet--tabs">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                        <i class="flaticon-share m--hide"></i>
                        <?php if((int)$data->focus_area[0] == 5 || (int)$data->focus_area[0] == 6): ?>
                            <?=$this->lang->get("StatusReport");?>
                        <?php else: ?>
                            <?=$this->lang->get("EvaluationReport");?>
                        <?php endif;?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="tab-content">
            <div class="tab-pane active" id="m_user_profile_tab_1">
                <div class="table-container">
                    <div class="table-actions-wrapper">
                        <span></span>
                        <select class="table-group-action-input form-control input-inline input-small input-sm">
                            <optgroup label="<?=$this->lang->get("Commands");?>">
                                <option value="false"><?=$this->lang->get("Select");?></option>
                                <option value="delete"><?=$this->lang->get("Delete");?></option>
                            </optgroup>
                            <optgroup label="<?=$this->lang->get("Status");?>">
                                <?php foreach($this->parameters->getList($this->lang, "report_statuses") as $value):?>
                                    <option value="status_<?=$value["id"];?>"><?=htmlspecialchars($value["title"]);?></option>
                                <?php endforeach;?>
                            </optgroup>
                        </select>
                        <button class="btn btn-sm yellow table-group-action-submit"><i class="fa fa-check"></i> <?=$this->lang->get("Execute");?></button>
                    </div>

                    <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                        <thead>
                        <tr role="row" class="heading">
                            <th width="2%"><input type="checkbox" class="group-checkable"></th>
                            <th><?=$this->lang->get("ID");?></th>
                            <th><?=$this->lang->get("Date");?></th>
                            <th><?=$this->lang->get("Status");?></th>
                            <th width="120"><?=$this->lang->get("Show", "Vis");?></th>
                        </tr>
                        <tr role="row" class="filter">
                            <td></td>
                            <td>
                            </td>
                            <td></td>
                            <td>
                                <select name="category" class="form-control form-filter input-sm">
                                    <option value=""><?=$this->lang->get("Select");?></option>
                                    <?php foreach($this->parameters->getList($this->lang, "report_statuses") as $value):?>
                                        <option value="<?=$value["id"];?>"><?=htmlspecialchars($value["title"]);?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                            <td>
                                <div class="margin-bottom-5" style="margin-bottom: 6px;">
                                    <button class="btn btn-sm yellow filter-submit"><i class="fa fa-search"></i> <?=$this->lang->get("Search");?></button>
                                </div>
                                <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> <?=$this->lang->get("Reset");?></button>
                            </td>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
