<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Add parameter</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <?php if($error):?>
                <p style="color: red;">
                    <?=$error;?>
                </p>
            <?php endif;?>
            <?php if($success):?>
                <p style="color: green;">
                    <?=$success;?>
                </p>
            <?php else:?>
                <input type="hidden" name="submit" value="1"/>
                <h4><?=Name;?>:</h4>
                <?php foreach($this->lang->langs as $value):?>
                    <div class="input-group margin-bottom-10">
                        <span class="input-group-addon" style="padding: 2px;;"><?=$value;?></span>
                        <input type="text" name="name[<?=$value;?>]" class="form-control input-lg" value="<?=@$this->request->get("name")[$value];?>"/>
                    </div>
                <?php endforeach;?>

            <?php endif;?>
        </div>
    </div>
</div>
<div class="modal-footer">
    <?php if(!$success):?>
    <button type="button" class="btn green" onclick="Fmodal.init('/<?=$controller;?>/add/<?=$id;?>?type=<?=$this->request->get("type");?>','html', 'post');"><?=Confirm;?></button>
    <?php endif;?>
    <a href="" class="btn"><?=Close;?></a>
</div>
