<!-- BEGIN PAGE HEADER-->
<style>
    .cat-setting{visibility: hidden;cursor: pointer;float: right;}
    .dd3-content:hover .cat-setting{visibility: visible;}
    .cat-options-a{display: block;padding: 5px 0 5px 10px;text-decoration: none;font-size: 15px;}
    .cat-options-a i{color: #444;}
    .input-car-index{height: 20px;width: 35px;margin:-4px 5px 0 0;}
    .input-car-active{float: left;margin:4px 5px 0 0 !important;}
</style>
<script>
    function gt(id){
        $("#catmodal").click();
        var h = '';
        h += '<a class="cat-options-a" href="javascript:Fmodal.init(\'/<?=$controller;?>/add/'+id+'?type=<?=$this->request->get("type");?>\', \'html\');"><i class="fa fa-plus"></i> Add</a>';
        h += '<a class="cat-options-a" href="javascript:Fmodal.init(\'/<?=$controller;?>/edit/'+id+'?type=<?=$this->request->get("type");?>\', \'html\');"><i class="fa fa-edit"></i> Edit</a>';
        h += '<a class="cat-options-a" href="javascript:Fmodal.init(\'/<?=$controller;?>/delete/'+id+'?type=<?=$this->request->get("type");?>\', \'html\');"><i class="fa fa-trash-o"></i> Delete</a>';
        $("#modal-body").html(h);
    }
</script>
<div class="row" style="display: none;">
    <div class="col-md-12">
        <h3>Serialised Output (per list)</h3>
        <textarea id="nestable_list_1_output" class="form-control col-md-12 margin-bottom-10"></textarea>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-comments"></i> Parameters / <?=$this->request->get("type");?>
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body ">
                <div class="dd" id="nestable_list_1">
                    <?php if (count(@$cat_arr[0]) > 0):?>
                        <ol class="dd-list">
                        <?php foreach($cat_arr[0] as $cat_id):?>
                        <li class="dd-item dd3-item" data-id="<?=$cat_id;?>">
                            <div class="dd-handle dd3-handle"></div>
                            <div class="dd3-content">
                                <input type="checkbox" class="input-car-active" value="1" cat_id="<?=$cat_id;?>" <?=($cat_data[$cat_id]["active"] == '1' ? "checked":"");?>/>
                                <?=$cat_data[$cat_id]["title"];?>
                                <i class="fa fa-wrench cat-setting" onclick="gt('<?=$cat_id;?>');"></i>
                            </div>
                            <?php if (count(@$cat_arr[$cat_id]) > 0):?>
                            <ol class="dd-list">
                                <?php foreach($cat_arr[$cat_id] as $cat_id2):?>
                                    <li class="dd-item dd3-item" data-id="<?=$cat_id2;?>">
                                        <div class="dd-handle dd3-handle"></div>
                                        <div class="dd3-content">
                                            <input type="checkbox" class="input-car-active" value="1" cat_id="<?=$cat_id2;?>" <?=($cat_data[$cat_id2]["active"] == '1' ? "checked":"");?>/>
                                            <?=$cat_data[$cat_id2]["title"];?>
                                            <i class="fa fa-wrench cat-setting" onclick="gt('<?=$cat_id2;?>');"></i>
                                        </div>
                                    </li>
                                    <?php if (count(@$cat_arr[$cat_id2]) > 0):?>
                                        <ol class="dd-list">
                                            <?php foreach($cat_arr[$cat_id2] as $cat_id3):?>
                                                <li class="dd-item dd3-item" data-id="<?=$cat_id3;?>">
                                                    <div class="dd-handle dd3-handle"></div>
                                                    <div class="dd3-content">
                                                        <input type="checkbox" class="input-car-active" value="1" cat_id="<?=$cat_id3;?>" <?=($cat_data[$cat_id3]["active"] == '1' ? "checked":"");?>/>
                                                        <?=$cat_data[$cat_id3]["title"];?>
                                                        <i class="fa fa-wrench cat-setting" onclick="gt('<?=$cat_id3;?>');"></i>
                                                    </div>
                                                </li>
                                            <?php endforeach;?>
                                        </ol>
                                    <?php endif;?>
                                <?php endforeach;?>
                            </ol>
                            <?php endif;?>
                        </li>
                        <?php endforeach;?>
                    </ol>
                    <?php else:?>
                        <div style="display: block;padding: 10px;color: red;"><?=NoCategoryAdded;?></div>
                    <?php endif;?>
                    <div style="display: block;padding: 5px;">
                        <a class="cat-options-a" href="javascript:Fmodal.init('/<?=$controller;?>/add/0?type=<?=$this->request->get("type");?>', 'html');"><i class="fa fa-plus"></i> Add parameter</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a class="btn default" id="catmodal" data-toggle="modal" href="#basic" style="display: none;"></a>
<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Options</h4>
            </div>
            <div class="modal-body" id="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn default" data-dismiss="modal"><?=Close;?></button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
