<?php if($controller !== "case"):?>
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?=$this->lang->get("CreateNew", "Opret ny");?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Offers");?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/add" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("CreateNew", "Opret ny");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<?php endif;?>

<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("CreateNew", "Opret ny");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else:?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("FocusArea", "Indsatsområde");?></label>
                        <div class="col-5">
                            <select id="focus_area" class="form-control m-input" name="focus_area" onchange="focusAreaChanged(this.value)">
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php $focusType = 1;?>
                                <?php foreach($this->parameters->getList($this->lang, "focusareas") as $key => $value):?>
                                    <?php if($key == 0) $focusType = (int)$value["id"];?>
                                    <option value="<?=(int)$value["id"];?>" <?=((int)$this->request->get("focus_area") == (int)$value["id"] ? 'selected="selected"': '');?>><?=$value["title"];?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("OfferType", "Offer type");?></label>
                        <div class="col-5" id="focus_types">
                            <select id="focus_area" class="form-control m-input" name="focus_type" onchange="offerTypeChanged(this.value)">
                                <?php foreach($this->parameters->getList($this->lang, "focustypes") as $key => $value):?>
                                    <option value="<?=(int)$value["id"];?>" <?=((int)$this->request->get("focus_type") == (int)$value["id"] ? 'selected="selected"': '');?>><?=$value["title"];?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Email", "E-mail Adresse");?></label>
                        <div class="col-5">
                            <input class="form-control m-input" name="email" type="text" value="<?=$this->request->get("email");?>">
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Phone");?></label>
                        <div class="col-5">
                            <input class="form-control m-input" name="phone" type="text" value="<?=$this->request->get("phone");?>">
                        </div>
                    </div>


                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"></label>
                        <div class="col-5">
                            <span style=""><input class="" name="is_secure" type="checkbox" value="1"></span> <span style="padding-left: 10px;"><?=$this->lang->get("SecureMail");?></span>
                        </div>
                    </div>

                    <style>
                        .note-editable{min-height: 900px;}
                    </style>
                    <div class="form-group m-form__group row">
                        <div class="col-12" id="summernote_body">
                            <textarea class="summernote" id="m_summernote_1" name="description" style="height: 900px;min-height: 900px;"><?=((int)$this->request->get("save") == 1 ? $this->request->get("description"): str_replace("{date}", date("d.m.Y"), file_get_contents("mailtemplates/focustypes/1.html")));?></textarea>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-3">
                        </div>
                        <div class="col-7">
                            <?php if($success):?>
                                <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                            <?php else:?>
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            <?php endif?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>

<script>
    function offerTypeChanged(offer_type){
        $.ajax({
                method: "POST",
                url: "/data/offertemplates",
                data: {offer_type: offer_type},
                dataType: "json",
            })
            .done(function(res){
                var html = '<textarea class="summernote" id="m_summernote_1" name="description" style="height: 900px;min-height: 900px;">'+res.data+'</textarea>';
                document.getElementById("summernote_body").innerHTML = html;
                SummernoteDemo.init();
            });
    }

    function focusAreaChanged(focusArea){
        focusArea = parseInt(focusArea);
        if(focusArea > 0){
            $.ajax({
                    method: "POST",
                    url: "/data/focustypes",
                    data: {focusarea: focusArea},
                    dataType: "json",
                })
                .done(function(res){
                    var html = '<select class="form-control m-input" name="focus_type" onchange="offerTypeChanged(this.value)">';
                    html += '<option value=""><?=$this->lang->get("None");?></option>';
                    for(var iii=0;iii<res.data.length;iii++){
                        var quest = res.data[iii];
                        html += '<option value="'+quest.id+'">'+quest.title+'</option>';
                    }
                    html += '</select>';
                    document.getElementById("focus_types").innerHTML = html;
                });
        }
    }

</script>