<div class="row">
<div class="col-md-12">

<!-- BEGIN PORTLET-->
<div class="portlet box yellow-crusta">
<div class="portlet-title">
    <div class="caption">
        <i class="fa fa-shopping-cart"></i> Translations
    </div>
</div>
<div class="portlet-body form">
<form action="" id="form-username" class="form-horizontal form-bordered" method="post">
<?php if ($success): ?>
    <div class="form-group">
        <label class="control-label col-md-3"></label>
        <div class="col-md-6">
            <div class="input-group" style="text-align:left;padding:0px;color: green;"><?=$success;?>. (<?=$added;?> keyword(s))</div>
        </div>
    </div>
<?php endif;?>
    <?php if ($error): ?>
        <div class="form-group">
            <label class="control-label col-md-3"></label>
            <div class="col-md-6">
                <div class="input-group" style="text-align:left;padding:0px;color: red;"><?=$error;?></div>
            </div>
        </div>
    <?php endif;?>
    <div class="form-group">
        <label class="col-sm-3 control-label">Lang <em>*</em></label>
        <div class="col-sm-6">
            <select name="lang" class="form-control form-filter input-sm">
                <option>Select</option>
                <?php foreach($this->language->langs as $value):?>
                    <option value="<?=$value;?>" <?=($value == $this->request->get("lang") ? "selected=\"selected\"": "");?>><?=$value;?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Keyword</label>
        <div class="col-sm-9">
            <input type="text" class="input form-control" name="keyword" value="<?=$this->request->get("keyword");?>"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Description</label>
        <div class="col-sm-9" style="padding-top: 15px;">
            <textarea style="display: block;height: 160px;width: 100%;" name="description"><?=$this->request->get("description");?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Sites</label>
        <div class="col-sm-9" style="padding-top: 15px;">
            <select name="sites[]" class="form-control select-md" multiple>
                <?php foreach($sites as $value):?>
                    <option value="<?=$value->id;?>" <?=((in_array($value->id, $this->request->get("sites"))) ? "selected=\"selected\"": "");?>>
                        <?=$value->id;?> - <?=$value->name;?>
                    </option>
                <?php endforeach;?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Tags</label>
        <div class="col-sm-9" style="padding-top: 15px;">
            <textarea style="display: block;height: 60px;width: 100%;" name="tags"><?=$this->request->get("tags");?></textarea>
        </div>
    </div>


    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn green" name="submit" value="1"><i class="fa fa-check"></i> Verify</button>
                <button type="reset" class="btn default">Cancel</button>
            </div>
        </div>
    </div>
</form>
</div>
</div>
<!-- END PORTLET-->
</div>
</div>