<script>
    var tablelisturl = '<?=_PANEL_ROOT_;?>/<?=$controller;?>/list?former=<?=(int)$this->request->get("former");?>';
</script>
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?php if((int)$this->request->get("former") == 0):?>
                    <?=$this->lang->get("Employees");?>
                <?php else: ?>
                    <?=$this->lang->get("FormerEmployees", "Former Employees");?>
                <?php endif;?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Employees", "Medarbejdere");?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Overview", "Oversigt");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__body">
            <?php if($this->auth->isPermitted($this->lang, $controller, "add")):?>
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1"></div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/add" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill"><span><i class="la la-user-plus"></i><span><?=$this->lang->get("CreateNew", "Opret ny");?></span></span></a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            <?php endif;?>
            <!--begin: Datatable -->
            <div class="table-container">
                <?php if($this->auth->isPermitted($this->lang, $controller, "delete")):?>
                    <div class="table-actions-wrapper">
                        <span></span>
                        <select class="table-group-action-input form-control input-inline input-small input-sm">
                            <option value="false"><?=$this->lang->get("Select");?></option>
                            <option value="active"><?=$this->lang->get("Active");?></option>
                            <option value="inactive"><?=$this->lang->get("Inactive");?></option>
                            <option value="">---------</option>
                            <option value="block"><?=$this->lang->get("Block");?></option>
                            <option value="unblock"><?=$this->lang->get("Unblock");?></option>
                            <option value="">---------</option>
                            <?php if((int)$this->request->get("former") == 0):?>
                                <option value="former"><?=$this->lang->get("MoveToFormers", "Move to formers");?></option>
                            <?php else: ?>
                                <option value="unformer"><?=$this->lang->get("UnMoveFromFormers", "Backup from formers");?></option>
                            <?php endif;?>
                            <option value="">---------</option>
                            <option value="delete"><?=$this->lang->get("Delete");?></option>
                        </select>
                        <button class="btn btn-sm yellow table-group-action-submit"><i class="fa fa-check"></i> <?=$this->lang->get("Execute");?></button>
                    </div>
                <?php endif;?>
                <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                    <thead>
                    <tr role="row" class="heading">
                        <th width="2%"><input type="checkbox" class="group-checkable"></th>
                        <th width="66"><?=$this->lang->get("ID");?></th>
                        <th><?=$this->lang->get("Firstname");?></th>
                        <th><?=$this->lang->get("Lastname");?></th>
                        <th><?=$this->lang->get("Address");?></th>
                        <th width="100"><?=$this->lang->get("ZipCode");?></th>
                        <th><?=$this->lang->get("City");?></th>
                        <th><?=$this->lang->get("PhoneNumber");?></th>
                        <th><?=$this->lang->get("Show", "Vis");?></th>
                    </tr>
                    <tr role="row" class="filter">
                        <td></td>
                        <td>
                            <input type="text" class="form-control form-filter input-sm search-input" name="item_id" autocomplete="off">
                        </td>
                        <td>
                            <input type="text" class="form-control form-filter input-sm search-input" name="firstname" autocomplete="off">
                        </td>
                        <td>
                            <input type="text" class="form-control form-filter input-sm search-input" name="lastname" autocomplete="off">
                        </td>
                        <td>
                            <input type="text" class="form-control form-filter input-sm search-input" name="address" autocomplete="off">
                        </td>
                        <td>
                            <input type="text" class="form-control form-filter input-sm search-input" name="zipcode" autocomplete="off">
                        </td>
                        <td>
                            <select name="city" class="form-control form-filter input-sm">
                                <option value=""><?=$this->lang->get("Select");?></option>
                                <?php foreach($this->parameters->getList($this->lang, "cities") as $value):?>
                                    <option value="<?=$value["id"];?>"><?=$value["title"];?></option>
                                <?php endforeach;?>
                            </select>
                        </td>
                        <td>
                            <input type="text" class="form-control form-filter input-sm search-input" name="phone" autocomplete="off">
                        </td>
                        <td>
                            <div class="margin-bottom-5" style="margin-bottom: 6px;">
                                <button class="btn btn-sm yellow filter-submit"><i class="fa fa-search"></i> <?=$this->lang->get("Search");?></button>
                            </div>
                            <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> <?=$this->lang->get("Reset");?></button>
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <!--end: Datatable -->
        </div>
    </div>
</div>
