<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("CreateNew", "Opret ny");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else:?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Title");?></label>
                        <div class="col-5">
                            <input class="form-control m-input" name="title" type="text" value="<?=$this->request->get("title");?>"/>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("For");?></label>
                        <div class="col-5">
                            <select class="form-control m-input" name="for" onchange="forChanged(this.value)">
                                <option value="citizen" <?=((string)$this->request->get("for") == "citizen" ? 'selected="selected"': '');?>><?=$this->lang->get("Citizen");?></option>
                                <option value="employee" <?=((string)$this->request->get("for") == "employee" ? 'selected="selected"': '');?>><?=$this->lang->get("Employee");?></option>
                            </select>
                        </div>
                    </div>




                    <div class="form-group m-form__group row">
                        <div class="col-9 ml-auto">
                            <h3 class="m-form__section"><?=$this->lang->get("DefaultSnippets", "Default snippets");?></h3>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-9 ml-auto">
                            <?=$this->lang->get("DefaultSnippetsText", "You can add these snippets where you want and your selections will be replaced with these snippets when you create contract for anyone");?>
                        </div>
                    </div>

                    <style>
                        .snippets-row{display: table;}
                        .snippets{display: table-cell;}
                        .snippets input{outline: none;border: 0;background: transparent;width: auto;padding: 8px; height: 34px;}
                        .snippets-separator{width: 20px;}
                        .snippets-bg{padding: 2px;background: #f1f1f1;border-radius: 5px;font-weight: 600;}
                    </style>
                    <div id="employee_snippets" style="display: none;margin-bottom: 20px;">
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Employee");?></label>
                            <div class="col-9">
                                <div class="snippets-row">
                                    <div class="snippets snippets-bg"><input value="{employee_name}"></div>
                                    <div class="snippets snippets-separator"></div>
                                    <div class="snippets snippets-bg"><input value="{employee_number}"></div>
                                    <div class="snippets snippets-separator"></div>
                                    <div class="snippets snippets-bg"><input value="{employee_address}"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="citizen_snippets" style="display: block;margin-bottom: 20px;">
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Citizen");?></label>
                            <div class="col-9">
                                <div class="snippets-row">
                                    <div class="snippets snippets-bg"><input value="{citizen_name}"></div>
                                    <div class="snippets snippets-separator"></div>
                                    <div class="snippets snippets-bg"><input value="{citizen_number}"></div>
                                    <div class="snippets snippets-separator"></div>
                                    <div class="snippets snippets-bg"><input value="{citizen_address}"></div>
                                </div>
                            </div>
                        </div>
                    </div>





                    <div class="form-group m-form__group row">
                        <div class="col-9 ml-auto">
                            <h3 class="m-form__section"><?=$this->lang->get("CustomSnippets", "Custom snippets");?></h3>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-9 ml-auto">
                            <?=$this->lang->get("CustomSnippetsText", "You can add these snippets where you want and your texts will be replaced with these snippets when you create contract for anyone");?>
                        </div>
                    </div>

                    <?php for($i=0;$i<5;$i++):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("CustomSnippet");?></label>
                        <div class="col-5">
                            <input class="form-control m-input" name="snippets[custom<?=$i+1;?>]" type="text" value="<?=('{custom'.($i+1).'}');?>" readonly="readonly">
                        </div>
                    </div>
                    <?php endfor;?>

                    <style>
                        .note-editable{min-height: 900px;}
                    </style>
                    <div class="form-group m-form__group row">
                        <div class="col-12" id="summernote_body">
                            <textarea class="summernote" id="m_summernote_1" name="description" style="height: 900px;min-height: 900px;"><?=((int)$this->request->get("save") == 1 ? $this->request->get("description"): file_get_contents("mailtemplates/example.html"));?></textarea>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-3">
                        </div>
                        <div class="col-7">
                            <?php if($success):?>
                                <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                            <?php else:?>
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            <?php endif?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>

<script>
    function offerTypeChanged(offer_type){
        $.ajax({
                method: "POST",
                url: "/data/offertemplates",
                data: {offer_type: offer_type},
                dataType: "json",
            })
            .done(function(res){
                var html = '<textarea class="summernote" id="m_summernote_1" name="description" style="height: 900px;min-height: 900px;">'+res.data+'</textarea>';
                document.getElementById("summernote_body").innerHTML = html;
                SummernoteDemo.init();
            });
    }

    function forChanged(forType){
        if(forType == "citizen"){
            document.getElementById("citizen_snippets").style.display = 'block';
            document.getElementById("employee_snippets").style.display = 'none';
        }else{
            document.getElementById("citizen_snippets").style.display = 'none';
            document.getElementById("employee_snippets").style.display = 'block';
        }

    }
</script>