<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8"/>
    <title>Admin Panel</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="/assetsx/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/assetsx/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/assetsx/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assetsx/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="/assetsx/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/assetsx/global/css/plugins.min.css" rel="stylesheet" type="text/css" />

    <?php $bodyclass = ''; ?>
    <?php if ($controller == "index"): ?>
        <link href="/assetsx/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
        <link href="/assetsx/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="/assetsx/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
    <?php elseif($controller == "profile"): ?>
        <link href="/assetsx/pages/css/profile.min.css" rel="stylesheet" type="text/css" />
    <?php elseif($action == "gallery"): ?>
        <link href="/assetsx/global/plugins/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css" rel="stylesheet"/>
        <link href="/assetsx/global/plugins/jquery-file-upload/css/jquery.fileupload.css" rel="stylesheet"/>
        <link href="/assetsx/global/plugins/jquery-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet"/>
    <?php elseif($action == "page"): ?>
        <link href="/assetsx/global/plugins/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css" rel="stylesheet"/>
        <link href="/assetsx/global/plugins/jquery-file-upload/css/jquery.fileupload.css" rel="stylesheet"/>
        <link href="/assetsx/global/plugins/jquery-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet"/>
    <?php elseif(in_array($controller, ["categories", "parameters", "countries"]) && in_array($action, ["index", "test"])): ?>
        <link rel="stylesheet" type="text/css" href="/assetsx/global/plugins/jquery-nestable/jquery.nestable.css"/>
    <?php endif; ?>
    <!-- END PAGE LEVEL PLUGIN STYLES -->
    <!-- BEGIN THEME STYLES -->
    <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
    <link href="/assetsx/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
    <link href="/assetsx/global/css/plugins.css" rel="stylesheet" type="text/css"/>

    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="/assetsx/layouts/layout4/css/layout.min.css?12345" rel="stylesheet" type="text/css" />
    <link href="/assetsx/layouts/layout4/css/themes/default.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/assetsx/layouts/layout4/css/custom.min.css" rel="stylesheet" type="text/css" />

    <link href="/resources/css/admin.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="/favicon.ico"/>
    <script>
        var panelroot = '';
    </script>
    <?php
    if (@$_COOIKE["sidebar_closed"] == '1')
        $bodyclass .= " page-sidebar-closed";
    ?>
</head>
<!-- END HEAD -->
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo <?=$bodyclass;?>">
<!-- BEGIN HEADER -->
<?php $this->view->partial("widgets/header"); ?>
<!-- END HEADER -->
<div class="clearfix">
</div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <?php $this->view->partial("widgets/sidebar"); ?>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <?php echo $this->getContent(); ?>
        </div>
    </div>

    <!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        <?=date("Y");?> &copy;
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<script>
    var Fmodal = {
        'requestType': 'json',
        'init': function(url, type){
            if (type)
                this.requestType = type;
            if ($("#main").css("display") !== "block"){
                $("#footermodal").click();
                var dataSent = {};
            }else{
                var dataSent = $("#footer-form").serialize();
            }
            $("#footer-modal").html('');
            if(this.requestType == 'json'){

            }

            var request = $.ajax({
                url: url,
                method: "POST",
                data: dataSent,
                dataType: this.requestType
            });

            request.done(function( msg ) {
                if (Fmodal.requestType == 'json'){
                    Fmodal.setTitle('Result');
                    if (msg.status == "success"){
                        Fmodal.setBody(msg.description);
                    }else if (msg.status == "error"){
                        Fmodal.setBody(msg.description);
                    }else{
                        Fmodal.setBody(msg);
                    }
                    Fmodal.setFooter('<button type="button" class="btn default" data-dismiss="modal">Close</button>');
                }else{
                    $("#footer-modal").append(msg);
                }
                $(".close").click(function(){
                    this.close();
                });
            });

        },
        'setTitle': function(title){
            var h = '<div class="modal-header">';
            h += '<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>';
            h += '<h4 class="modal-title">'+title+'</h4>';
            h += '</div>';
            $("#footer-modal").append(h);
        },
        'setBody': function(body){
            var h = '<div class="modal-body" id="footer-modal-body">';
            h += body;
            h += '</div>';
            $("#footer-modal").append(h);
        },
        'setFooter': function(footer){
            var h = '<div class="modal-footer">';
            h += footer;
            h += '</div>';
            $("#footer-modal").append(h);
        },
        'close': function(){
            $("#footer-modal").html('');
        }
    }

</script>
<a class="btn default" id="footermodal" data-toggle="modal" href="#main" style="display: none;"></a>
<div class="modal fade" id="main" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <form id="footer-form" action="" method="post">
            <div class="modal-content" id="footer-modal">

            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<?php $this->view->partial("widgets/javascripts"); ?>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>