<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("Write");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else:?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Moderators");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_4" name="moderator[]" multiple>
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($moderators as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((in_array($value->id, $this->request->get("moderator"))) ? 'selected="selected"': '');?>><?=htmlspecialchars($value->firstname." ".$value->lastname);?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Citizens");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_1" name="citizen[]" multiple>
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($citizens as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((in_array($value->id, $this->request->get("citizen"))) ? 'selected="selected"': '');?>><?=$value->firstname;?> <?=$value->lastname;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Employees");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_2" name="employee[]" multiple>
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($employees as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((in_array($value->id, $this->request->get("employee"))) ? 'selected="selected"': '');?>><?=$value->firstname;?> <?=$value->lastname;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Partners");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_3" name="partner[]" multiple>
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($partners as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((in_array($value->id, $this->request->get("partner"))) ? 'selected="selected"': '');?>><?=$value->firstname;?> <?=$value->lastname;?> (Partner ID: <?=$value->partner;?>)</option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Message");?></label>
                        <div class="col-7">
                            <textarea class="form-control" name="message" style="min-height: 200px;"><?=$this->request->get("message");?></textarea>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-7">
                            <?php if($success):?>
                                <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                            <?php else:?>
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Send");?></button>&nbsp;&nbsp;
                            <?php endif?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>