<div class="m-portlet m-portlet--full-height m-portlet--tabs  ">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                        <i class="flaticon-share m--hide"></i>
                        <?=$this->lang->get("Contracts");?>
                    </a>
                </li>
            </ul>

            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="<?=_PANEL_ROOT_;?>/profile/contractsadd/<?=$id;?>" class="m-portlet__nav-link btn btn-secondary m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill">
                        <i class="la la-plus"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-pane active" id="m_user_profile_tab_1">
            <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-12">
                            <?php if(count($contracts) > 0):?>
                                <?php foreach($contracts as $key => $value):?>
                                        <div class="col-12">
                                            <a href="<?=_PANEL_ROOT_;?>/contracts/view/<?=$value->id;?>">
                                                <?=$key+1;?>) <?=$this->mymongo->dateFormat($value->created_at, "Y-m-d H:i");?>
                                            </a>
                                        </div>
                                <?php endforeach;?>
                            <?php else: ?>
                                <div style="color: red;"><?=$this->lang->get("NotFoundDocument", "Document not found");?></div>
                            <?php endif;?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>