<div class="m-portlet m-portlet--full-height m-portlet--tabs  ">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                        <i class="flaticon-share m--hide"></i>
                        <?=$this->lang->get("CreateNew");?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-pane active" id="m_user_profile_tab_1">
            <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
                <div class="m-portlet__body">
                    <?php if($success):?>
                        <div class="form-group m-form__group row">
                            <div class="form-success">
                                <?=$success;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>

                    <?php if(count($contracts) > 0):?>
                        <?php foreach($contracts as $key => $value):?>
                            <div class="">
                                <div class="col-12">
                                    <a href="<?=_PANEL_ROOT_;?>/contracts/send/<?=$value->id;?>?citizen=<?=($data->type == "citizen" ? $id: 0);?>&employee=<?=($data->type == "employee" ? $id: 0);?>">
                                        <b><?=$key+1;?>) <?=htmlspecialchars($value->title);?></b>
                                    </a>
                                </div>
                            </div>
                        <?php endforeach;?>
                    <?php else: ?>
                        <div style="color: red;"><?=$this->lang->get("NotFoundDocument", "Document not found");?></div>
                    <?php endif;?>
                </div>
            </form>
        </div>
    </div>
</div>