<div class="m-portlet m-portlet--full-height m-portlet--tabs  ">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                        <i class="flaticon-share m--hide"></i>
                        <?=$this->lang->get("UserProfile", "Profile");?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-pane active" id="m_user_profile_tab_1">
            <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
                <div class="m-portlet__body">
                    <?php if($success):?>
                        <div class="form-group m-form__group row">
                            <div class="form-success">
                                <?=$success;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="form-group m-form__group row">
                        <div class="col-9 ml-auto">
                            <h3 class="m-form__section">1. <?=$this->lang->get("PersonalInformation", "Personlige Oplysninger");?></h3>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Firstname", "Fornavn");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="firstname" type="text" value="<?=htmlspecialchars($data->firstname);?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Lastname", "Efternavn");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="lastname" type="text" value="<?=htmlspecialchars($data->lastname);?>">
                        </div>
                    </div>

                    <?php if($data->type == "user"):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("LeakbotID", "Leakbot ID");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="leakbot_id" type="text" value="<?=htmlspecialchars($data->leakbot_id);?>">
                        </div>
                    </div>
                    <?php endif;?>

                   <?php if($data->type == "employee"):?>
                       <div class="form-group m-form__group row">
                           <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Group");?></label>
                           <div class="col-7">
                               <select class="form-control" name="type2">
                                   <?php foreach($this->parameters->getList($this->lang, "employee_types") as $value):?>
                                       <option value="<?=(int)$value["id"];?>" <?=((int)$value["id"] == (int)$data->type2 ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                   <?php endforeach;?>
                               </select>
                           </div>
                       </div>
                    <?php endif;?>


                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("PhoneNumber", "Telefonnummer");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="phone" type="text" value="<?=htmlspecialchars($data->phone);?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Email", "E-mail Adresse");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="email" type="text" value="<?=htmlspecialchars($data->email);?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Gender", "Køn");?></label>
                        <div class="col-7">
                            <select class="form-control m-input" name="gender">
                                <option value=""><?=$this->lang->get("Choose");?></option>
                                <option value="male" <?=($data->gender == "male" ? 'selected="selected"': '');?>><?=$this->lang->get("Male", "Mand");?></option>
                                <option value="female" <?=($data->gender == "female" ? 'selected="selected"': '');?>><?=$this->lang->get("Female", "Kvinde");?></option>
                            </select>
                        </div>
                    </div>




                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Address", "Adresse");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="address" type="text" value="<?=htmlspecialchars($data->address);?>">
                        </div>
                    </div>


                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Partner");?></label>
                        <div class="col-7">
                            <select class="form-control m-input" name="partner" onchange="partnerChanged(this.value)">
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($partners as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((int)$data->partner == (int)$value->id ? 'selected="selected"': '');?>><?=$value->name;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>


                </div>
                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <div class="row">
                            <div class="col-3">
                            </div>
                            <div class="col-7">
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="tab-pane " id="m_user_profile_tab_2">

        </div>
        <div class="tab-pane " id="m_user_profile_tab_3">

        </div>
    </div>
</div>