<div class="m-portlet m-portlet--full-height m-portlet--tabs  ">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                        <i class="flaticon-share m--hide"></i>
                        <?=$this->lang->get("Edit");?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-pane active" id="m_user_profile_tab_1">
            <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
                <div class="m-portlet__body">
                    <?php if($success):?>
                        <div class="form-group m-form__group row">
                            <div class="form-success">
                                <?=$success;?>
                            </div>
                        </div>
                    <?php else:?>
                        <?php if($error):?>
                            <div class="form-group m-form__group row">
                                <div class="form-error">
                                    <?=$error;?>
                                </div>
                            </div>
                        <?php endif;?>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("NoteName", "Notat navn");?></label>
                            <div class="col-7">
                                <input class="form-control m-input" name="title" type="text" value="<?=htmlspecialchars($notedata->title);?>">
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Description");?></label>
                            <div class="col-7">
                                <textarea class="form-control" name="description" style="min-height: 200px;"><?=htmlspecialchars($notedata->description);?></textarea>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <div class="row">
                            <div class="col-2">
                            </div>
                            <div class="col-7">
                                <?php if($success):?>
                                    <a href="<?=_PANEL_ROOT_;?>/profile/notes/<?=$id;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                                <?php else:?>
                                    <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                                <?php endif?>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>