<html>
<head>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="text-align: center;background: #f1f1f1;padding: 0;margin:0;">
<div style="width: 100%;max-width: 800px;margin: 0 auto;background: white;padding: 20px;">
    <div style="display: block;height: 220px;text-align: center;">
        <img style="margin: auto;width: 100%;max-width: 240px;margin-top: 30px;" src="http://arc.carecompagniet.dk/mailtemplates/image001.jpg"/>
    </div>

    <div style="text-align: left;">

        <div style="display: block;">
        <div style="width: 100%;max-width: 300px;margin: 20px auto;">
            <form action="" method="post">
                <?php if($error): ?>
                    <div style="display: block;margin-bottom: 15px;text-align: left;color: red;font-size: 14px;">
                        <?=$error;?>
                    </div>
                <?php endif;?>
                <div style="display: block;margin-bottom: 15px;">
                    <input type="text" name="code" value="" placeholder="<?=$this->lang->get("VerificationCode");?>" style="width: 100%;height:35px;border: 1px solid #e1e1e1;border-radius: 4px;font-size: 14px;background: #f5f5f5;padding: 4px 10px;" autocomplete="off"/>
                </div>
                <div style="display: block;margin-bottom: 15px;">
                    <input type="submit" name="submit" value="<?=$this->lang->get("View");?>" style="width: 100%;height:35px;border: 1px solid #85c226;border-radius: 4px;font-size: 14px;background: #85c226;padding: 4px 10px;color: white;cursor: pointer;"/>
                </div>
            </form>
        </div>
        </div>

        <p>

        </p>
    </div>
</div>
</body>
</html>