<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?=$title;?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>?type=<?=$type;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$title;?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/edit/<?=$data->id;?>?type=<?=$type;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Edit", "Edit");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("Edit", "Edit");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php endif;?>
                <?php if($error):?>
                    <div class="form-group m-form__group row">
                        <div class="form-error">
                            <?=$error;?>
                        </div>
                    </div>
                <?php endif;?>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Name");?></label>
                    <div class="col-7">
                        <?php foreach($this->lang->langs as $value):?>
                            <div style="width: 100%;margin-bottom: 8px;display: table;">
                                <div style="width: 50px;padding-top: 8px;text-align: center;display: table-cell;background: #e1e1e1;"><?=$value;?></div>
                                <div style="wisplay: table-cell;"><input class="form-control m-input" name="titles[<?=$value;?>]" type="text" value="<?=@$data->titles->{$value};?>" autocomplete="off"></div>
                            </div>
                        <?php endforeach;?>
                    </div>
                </div>
                <?php if($type == "goals"):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("FocusArea", "Indsatsområde");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_3" name="focus_area[]" multiple="multiple">
                                <optgroup label="">
                                    <?php foreach($this->parameters->getList($this->lang, "focus_areas") as $value):?>
                                        <option value="<?=(int)$value["id"];?>" <?=((in_array((int)$value["id"], $data->focus_area)) ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                    <?php endforeach;?>
                                </optgroup>
                            </select>
                        </div>
                    </div>
                <?php elseif($type == "cities"):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("PostNumber");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="post_number" type="text" value="<?=htmlspecialchars($data->post_number);?>" autocomplete="off" placeholder="0000">
                        </div>
                    </div>
                <?php elseif($type == "system_languages"):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("2LetterCode", "Slug (2 Letters code)");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="code" type="text" value="<?=htmlspecialchars($data->code);?>" autocomplete="off" placeholder="en">
                        </div>
                    </div>
                <?php elseif($type == "focustypes"):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("FocusArea", "Indsatsområde");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_3" name="focus_area">
                                <?php foreach($this->parameters->getList($this->lang, "focus_areas") as $value):?>
                                    <option value="<?=(int)$value["id"];?>" <?=((int)$value["id"] == (int)$data->focus_area ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                <?php elseif($type == "questions"):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("CaseCategories");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_3" name="category[]" multiple="multiple">
                                <optgroup label="">
                                    <?php foreach($this->parameters->getList($this->lang, "case_categories") as $value):?>
                                        <option value="<?=(int)$value["id"];?>" <?=((in_array((int)$value["id"], $data->category)) ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                    <?php endforeach;?>
                                </optgroup>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Goals");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_4" name="goal[]">
                                <optgroup label="">
                                    <?php foreach($this->parameters->getList($this->lang, "goals") as $value):?>
                                        <option value="<?=(int)$value["id"];?>" <?=((in_array((int)$value["id"], $data->goal)) ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                    <?php endforeach;?>
                                </optgroup>
                            </select>
                        </div>
                    </div>
                <?php elseif(in_array($type, ["colors","activity_statuses","trading_plan_statuses","todo_categories","report_statuses","calendar_statuses"])):?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("HtmlCode", "HTML code");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" id="colorpicker-popup" name="html_code" type="text" value="<?=substr(htmlspecialchars($data->html_code),1);?>" autocomplete="off" placeholder="#e1e1e1">
                        </div>
                    </div>
                <?php endif;?>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Status");?></label>
                    <div class="col-7">
                        <select class="form-control m-input" name="active">
                            <option value="1" <?=((int)$data->active == 1 ? 'selected="selected"': '');?>><?=$this->lang->get("Active");?></option>
                            <option value="0" <?=((int)$data->active == 0 ? 'selected="selected"': '');?>><?=$this->lang->get("Deactive");?></option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-7">
                            <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            <!--<a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>?type=<?=$type;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;-->
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>