<!-- BEGIN PAGE HEADER-->
<script>
    var tablelisturl = <?=_ROOT_;?>'/<?=$controller;?>/list';
</script>
<style>
    .prop-btn{margin-bottom: 5px;}
</style>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-shopping-cart"></i> Translations
                </div>

                <div class="actions">
                    <a href="<?=_ROOT_;?>/<?=$controller;?>/excel" class="btn default yellow-stripe">
                        <i class="fa fa-angle-double-right"></i>
                        <span class="hidden-480">Excel</span>
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                        <thead>
                        <tr role="row" class="heading">
                            <th width="2%"><input type="checkbox" class="group-checkable"></th>
                            <th width="15%">Key</th>
                            <th width="35%">Original</th>
                            <th width="35%">Translation</th>
                            <th width="">Template ID</th>
                            <th width="">Actions</th>
                        </tr>
                        <tr role="row" class="filter">
                            <td></td>
                            <td>
                                <input type="text" class="form-control form-filter input-sm" name="key">
                            </td>
                            <td>
                                <select class="form-control form-filter select margin-bottom-10" name="from_lang">
                                    <?php foreach($this->lang->testLangs as $key => $value):?>
                                        <option value="<?=$value;?>" <?=($key == 0 ? 'selected="selected"': '');?>><?=$value;?></option>
                                    <?php endforeach;?>
                                </select>
                                <input type="text" class="form-control form-filter input-sm" name="from_original">
                            </td>
                            <td>
                                <select class="form-control form-filter select margin-bottom-10" name="to_lang">
                                    <?php foreach($this->lang->testLangs as $key => $value):?>
                                        <option value="<?=$value;?>" <?=($key == 1 ? 'selected="selected"': '');?>><?=$value;?></option>
                                    <?php endforeach;?>
                                </select>
                                <input type="text" class="form-control form-filter input-sm" name="to_original">
                            </td>
                            <td>
                                <select class="form-control form-filter select" name="template_id">
                                    <option value="0">All</option>
                                    <?php foreach($this->lang->templates as $key => $value):?>
                                        <option value="<?=$key;?>"><?=$value["name"];?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                            <td>
                                <div class="margin-bottom-5">
                                    <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
                                </div>
                                <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                            </td>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
<script>
    function editKeyword(uuid, lang, dataMetod, fromLang){
        Fmodal.init("<?=_ROOT_;?>/<?=$controller;?>/edit?uuid="+uuid+"&current_lang="+lang+"&from_lang="+fromLang, "html", dataMetod);
    }
</script>
