<script>
    var tablelisturl = '<?=_PANEL_ROOT_;?>/<?=$controller;?>/list';
</script>
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                    <?=$this->lang->get("CasesList", "Liste over sager");?>
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Cases", "Sager");?></span></a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("CasesList", "Liste over sager");?></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__body">
                <?php if($this->auth->isPermitted($this->lang, $controller, "add")):?>
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1"></div>
                        <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                            <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/add" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill"><span><i class="la la-user-plus"></i><span><?=$this->lang->get("CreateNew", "Opret ny");?></span></span></a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>
                <?php endif;?>
                <!--begin: Datatable -->
                <div class="table-container">
                    <?php if($this->auth->isPermitted($this->lang, $controller, "delete")):?>
                    <div class="table-actions-wrapper">
                        <span></span>
                        <select class="table-group-action-input form-control input-inline input-small input-sm">
                            <option value="false"><?=$this->lang->get("Select");?></option>
                            <option value="delete"><?=$this->lang->get("Delete");?></option>
                        </select>
                        <button class="btn btn-sm yellow table-group-action-submit"><i class="fa fa-check"></i> <?=$this->lang->get("Execute");?></button>
                    </div>
                    <?php endif;?>

                    <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                        <thead>
                        <tr role="row" class="heading">
                            <th width="2%"><input type="checkbox" class="group-checkable"></th>
                            <th width="10%"><?=$this->lang->get("CaseNumber", "Sagsnummer");?></th>
                            <th><?=$this->lang->get("Employee", "Employee");?></th>
                            <th><?=$this->lang->get("Citizen", "Borger");?></th>
                            <th><?=$this->lang->get("FocusArea", "Indsatsområde");?></th>
                            <th><?=$this->lang->get("FocusType", "Indsatstype");?></th>
                            <th><?=$this->lang->get("Show", "Vis");?></th>
                        </tr>
                        <tr role="row" class="filter">
                            <td></td>
                            <td>
                                <input type="text" class="form-control form-filter input-sm" name="item_id">
                            </td>
                            <td>
                                <select name="citizen" class="form-control form-filter input-sm">
                                    <option value=""><?=$this->lang->get("Select");?></option>
                                    <?php foreach($employees as $key => $value):?>
                                        <option value="<?=$value->id;?>"><?=htmlspecialchars($value->firstname);?> <?=htmlspecialchars($value->lastname);?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                            <td>
                                <select name="citizen" class="form-control form-filter input-sm">
                                    <option value=""><?=$this->lang->get("Select");?></option>
                                    <?php foreach($citizens as $key => $value):?>
                                        <option value="<?=$value->id;?>"><?=htmlspecialchars($value->firstname);?> <?=htmlspecialchars($value->lastname);?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                            <td>
                                <select name="focus_area" class="form-control form-filter input-sm">
                                    <option value=""><?=$this->lang->get("Select");?></option>
                                    <?php foreach($this->parameters->getList($this->lang, "focusareas") as $value):?>
                                        <option value="<?=$value["id"];?>"><?=htmlspecialchars($value["title"]);?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                            <td>
                                <select name="focus_type" class="form-control form-filter input-sm">
                                    <option value=""><?=$this->lang->get("Select");?></option>
                                    <?php foreach($this->parameters->getList($this->lang, "focustypes") as $value):?>
                                        <option value="<?=$value["id"];?>"><?=htmlspecialchars($value["title"]);?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                            <td>
                                <div class="margin-bottom-5" style="margin-bottom: 6px;">
                                    <button class="btn btn-sm yellow filter-submit"><i class="fa fa-search"></i> <?=$this->lang->get("Search");?></button>
                                </div>
                                <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> <?=$this->lang->get("Reset");?></button>
                            </td>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <!--end: Datatable -->
            </div>
        </div>
    </div>
