<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="<?=_ROOT_;?>/" style="text-decoration: none;">
                <h2 class="logo-default" style="position: absolute;
    top: 25px;
    left: 24px;
    margin: 0;
    font-size: 22px;
    font-weight: 500;"><font style="color: #d6d3d3;"><?=strtoupper(COMPANY_NAME);?></font></h2>
            </a>
            <div class="menu-toggler sidebar-toggler">
                <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN PAGE ACTIONS -->
        <!-- BEGIN PAGE TOP -->
        <div class="page-top">
            <!-- BEGIN HEADER SEARCH BOX -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown dropdown-language">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="true">
                            <img alt="" src="/assetsx/global/img/flags/<?=str_replace(["en"],["us"],$this->lang->getLang());?>.png">
                            <span class="langname"> <?=strtoupper($this->lang->getLang());?> </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <?php foreach($this->lang->langs as $value):?>
                                <?php if($value !== $this->lang->getLang()):?>
                                    <li>
                                        <a href="?lang=<?=$value;?>">
                                            <img alt="" src="/assetsx/global/img/flags/<?=str_replace(["en"],["us"],$value);?>.png"> <?=$this->lang->langData[$value]["name"];?>
                                        </a>
                                    </li>
                                <?php endif;?>
                            <?php endforeach;?>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END PAGE TOP -->
    </div>
    <!-- END HEADER INNER -->
</div>