<!-- BEGIN CORE PLUGINS -->
<script src="/assetsx/global/plugins/jquery.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/global/plugins/bootstrap/js/bootstrap.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/global/plugins/js.cookie.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/global/plugins/jquery.blockui.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js?32123" type="text/javascript"></script>
<!-- END CORE PLUGINS -->

<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="/assetsx/global/scripts/app.min.js?32123" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->

<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="/assetsx/layouts/layout4/scripts/layout.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/layouts/layout4/scripts/demo.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/layouts/global/scripts/quick-sidebar.min.js?32123" type="text/javascript"></script>
<script src="/assetsx/layouts/global/scripts/quick-nav.min.js?32123" type="text/javascript"></script>
<!-- END THEME LAYOUT SCRIPTS -->

<?php if ($controller == "index"): ?>
    <script src="/assetsx/global/plugins/flot/jquery.flot.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/flot/jquery.flot.resize.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/flot/jquery.flot.categories.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/jquery.pulsate.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-daterangepicker/moment.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-daterangepicker/daterangepicker.js?32123" type="text/javascript"></script>
    <!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
    <script src="/assetsx/global/plugins/fullcalendar/fullcalendar.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/jquery.sparkline.min.js?32123" type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/global/scripts/metronic.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/layout.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/quick-sidebar.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/demo.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/pages/scripts/index.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/pages/scripts/tasks.js?32123" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function() {
            Metronic.init(); // init metronic core componets
            Layout.init(); // init layout
            Demo.init(); // init demo features
            Index.init();
        });
    </script>
<?php elseif(in_array($controller, ["photos"]) && in_array($action, ["edit"])): ?>
    <script src="/assetsx/global/plugins/jcrop/js/jquery.color.js?32123"></script>
    <script src="/assetsx/global/plugins/jcrop/js/jquery.Jcrop.min.js?32123"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/global/scripts/metronic.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/layout.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/quick-sidebar.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/demo.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/pages/scripts/form-image-crop.js?32123"></script>
    <script>
        jQuery(document).ready(function(){
            Metronic.init(); // init metronic core componets
            Layout.init(); // init layout
            FormImageCrop.init();
        });
    </script>
<?php elseif(in_array($controller, ["orders"]) && in_array($action, ["edit"])): ?>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assets/global/scripts/metronic.js" type="text/javascript"></script>
    <script src="/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
    <script src="/assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
    <script src="/assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
    <script>
        LangD = {
            fromAddress: 'From',
            toAddress: 'To',
            nextAddress: 'Next address',
            searching: 'Searching...',
            calculating: 'Calculating...',
            connectionError: '<?=$this->lang->get("lConnectionError");?>',
        }
    </script>
    <script src="/resources/js/addresses.js?<?=rand(1,10000000);?>"></script>
    <script>
        var addresses = [
            {
                name: <?=(strlen($data->address_from) > 0 ? "'".$data->address_from."'": "''")?>,
                state: "",
                place_id: <?=(strlen($data->place_id_from) > 0 ? "'".$data->place_id_from."'": 'false')?>,
                location: <?=((float)@$data->geo_location_from["latitude"] > 0 ? "{latitude: ".@$data->geo_location_from["latitude"].", longitude: ".@$data->geo_location_from["longitude"]."}": 'false');?>,
            }
        ];
        <?php if($data && count($data->waypoints) > 0):?>
        <?php foreach($data->waypoints as $value):?>
        addresses[addresses.length] = {
            name: <?=(strlen($value["address"]) > 0 ? "'".$value["address"]."'": "''")?>,
            state: "",
            place_id: <?=(strlen($value["place_id"]) > 0 ? "'".$value["place_id"]."'": 'false')?>,
            location: <?=((float)@$value["geo_location"]["latitude"] > 0 ? "{latitude: ".@$value["geo_location"]["latitude"].", longitude: ".@$value["geo_location"]["longitude"]."}": 'false');?>,
        };
        <?php endforeach;?>
        <?php endif;?>
        addresses[addresses.length] = {
            name: <?=(strlen($data->address_to) > 0 ? "'".$data->address_to."'": "''")?>,
            state: "",
            place_id: <?=(strlen($data->place_id_to) > 0 ? "'".$data->place_id_to."'": 'false')?>,
            location: <?=((float)@$data->geo_location_to["latitude"] > 0 ? "{latitude: ".@$data->geo_location_to["latitude"].", longitude: ".@$data->geo_location_to["longitude"]."}": 'false');?>,
        };
    </script>
    <script>
        jQuery(document).ready(function() {
            Metronic.init(); // init metronic core componets
            Layout.init(); // init layout
            OOrder.init();
        });
    </script>
<?php elseif(in_array($controller, ["profile"])): ?>
    <script src="/assetsx/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/gmaps/gmaps.min.js" type="text/javascript"></script>

    <script src="/assetsx/pages/scripts/profile.min.js" type="text/javascript"></script>
    <script src="/assetsx/pages/scripts/timeline.min.js" type="text/javascript"></script>

    <script type="text/javascript" src="/resources/js/uploadphoto.js?<?=rand(1,999999999);?>"></script>

    <script>
        $(document).ready(function()
        {
            $('#clickmewow').click(function()
            {
                $('#radio1003').attr('checked', 'checked');
            });
        })
    </script>
<?php elseif(in_array($controller, ["rates", "smslogs", "cities", "cars", "tariffs", "currencies", "partners", "partnermoderators", "orders", "messages","users", "moderators", "pages", "translations", "videos", "tempusers", "notifications", "transactions", "withdraws", "apilogs"]) && in_array($action, ["index"])): ?>
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="/assetsx/global/scripts/datatable.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/datatables/datatables.min.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js?32123" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js?32123" type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/pages/scripts/table-datatables-buttons.min.js?32123" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->

    <script>
        $(document).ready(function()
        {
            $('#clickmewow').click(function()
            {
                $('#radio1003').attr('checked', 'checked');
            });
        })
    </script>
<?php elseif(in_array($controller, ["moderators"]) && in_array($action, ["edit"])): ?>
    <script src="/resources/js/permission.js" type="text/javascript"></script>
    <script>
        $(document).ready(function()
        {
            $('#clickmewow').click(function()
            {
                $('#radio1003').attr('checked', 'checked');
            });
        })
        PPermission.init();
    </script>
<?php elseif(in_array($controller, ["categories", "insights", "pages", "news"]) && in_array($action, ["page"])): ?>
    <script src="/assetsx/global/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/js.cookie.min.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="/assetsx/global/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-markdown/lib/markdown.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
    <script src="/assetsx/global/plugins/bootstrap-summernote/summernote.min.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <script src="/assetsx/global/scripts/app.min.js" type="text/javascript"></script>
    <!-- END THEME GLOBAL SCRIPTS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/pages/scripts/components-editors.min.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <!-- BEGIN THEME LAYOUT SCRIPTS -->
    <script src="/assetsx/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
    <script src="/assetsx/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
    <script src="/assetsx/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
    <script src="/assetsx/layouts/global/scripts/quick-nav.min.js" type="text/javascript"></script>
    <link href="/assetsx/global/plugins/bootstrap-summernote/summernote.css" rel="stylesheet" type="text/css" />

    <script>
        $(document).ready(function()
        {
            $('#clickmewow').click(function()
            {
                $('#radio1003').attr('checked', 'checked');
            });
        })

        jQuery(document).ready(function(){
            $(".input-car-index").keyup(function(){
                var catId = $(this).attr("cat_id");
                //alert( "<?=_ROOT_;?>/categories/setindex/"+catId+"?index_id="+$(this).val());
                var jqxhr = $.ajax("<?=_ROOT_;?>/<?=$controller;?>/setindex/"+catId+"?index_id="+$(this).val())
                    .done(function() {
                    })
            });
            $(".input-car-active").click(function(){
                var catId = $(this).attr("cat_id");
                //alert( "<?=_ROOT_;?>/categories/setindex/"+catId+"?index_id="+$(this).val());
                var jqxhr = $.ajax("<?=_ROOT_;?>/<?=$controller;?>/setvisible/"+catId+"?status="+($(this).is(':checked') ? 1: 0))
                    .done(function() {
                    })
            });
        });

        function setCatIndex(carId, indexId){

        }
    </script>
<?php elseif($action == "gallery"): ?>
    <!-- The blueimp Gallery widget -->
    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
        <div class="slides">
        </div>
        <h3 class="title"></h3>
        <a class="prev">
            ‹ </a>
        <a class="next">
            › </a>
        <a class="close white">
        </a>
        <a class="play-pause">
        </a>
        <ol class="indicator">
        </ol>
    </div>
    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <script id="template-upload" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr class="template-upload fade">
                <td></td>
                <td>
                    <span class="preview"></span>
                </td>
                <td>
                    <p class="name">{%=file.name%}</p>
                    <strong class="error text-danger label label-danger"></strong>
                </td>
                <td>
                    <p class="size">Processing...</p>
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                    </div>
                </td>
                <td>
                    {% if (!i && !o.options.autoUpload) { %}
                        <button class="btn blue start" disabled>
                            <i class="fa fa-upload"></i>
                            <span>Start</span>
                        </button>
                    {% } %}
                    {% if (!i) { %}
                        <button class="btn red cancel">
                            <i class="fa fa-ban"></i>
                            <span>Cancel</span>
                        </button>
                    {% } %}
                </td>
            </tr>
        {% } %}
    </script>
    <!-- The template to display files available for download -->
    <script id="template-download" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr class="template-download fade">
                <td width="20">
                    {% if (file.deleteUrl) { %}
                        <input type="checkbox" name="delete" value="1" class="toggle">
                    {% } %}
                </td>
                <td width="100">
                    <span class="preview">
                    {% if (file.file_type == 'video') { %}
                            <video width="100%" controls="">
                                <source src="{%=file.videoUrl%}" type="video/mp4">
                                Your browser does not support HTML5 video.
                            </video>
                    {% } else { %}
                        {% if (file.thumbnailUrl) { %}
                            <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery>
                                <img width="80" height="80" src="{%=file.thumbnailUrl%}">
                            </a>
                        {% }else{ %}
                            <video width="100%" controls="">
                                <source src="{%=file.videoUrl%}" type="video/mp4">
                                Your browser does not support HTML5 video.
                            </video>
                        {% } %}
                    {% } %}
                    </span>
                </td>
                <td>
                    {% if (file.file_type == 'video') { %}

                    {% } else { %}
                    <img onclick="mainPhoto('{%=file.id%}')" id="galleryimage{%=file.id%}" class="galleryimage" src="/resources/images/main_is{%=(file.is_main == 0 ? '_not': '')%}.png"/>
                    <span class="gallery-span-name"> = is header picture</span>
                    <div style="clear:both;height:5px;"></div>
                    <img onclick="isrightPhoto('{%=file.id%}')" id="galleryright{%=file.id%}" class="galleryright" src="/resources/images/main_is{%=(file.is_right == 0 ? '_not': '')%}.png"/>
                    <span class="gallery-span-name"> = is on right side (or by default left)</span>
                    <div style="clear:both;height:5px;"></div>
                    <img onclick="islogoPhoto('{%=file.id%}')" id="gallerylogo{%=file.id%}" class="gallerylogo" src="/resources/images/main_is{%=(file.is_logo == 0 ? '_not': '')%}.png"/>
                    <span class="gallery-span-name"> = is logo</span>
                    <div style="clear:both;height:5px;"></div>
                    <img onclick="isfullPhoto('{%=file.id%}')" id="galleryfull{%=file.id%}" class="gallerylogo" src="/resources/images/main_is{%=(file.is_full == 0 ? '_not': '')%}.png"/>
                    <span class="gallery-span-name"> = is full</span>
                    {% } %}
                </td>
                <td>
                    {% if (file.is_pdf == '1') { %}
                        <span class="gallery-span">{%=file.name%}</span>
                    {% } else { %}
                        <span class="gallery-span">[img:{%=file.id%}]</span>
                    {% } %}
                </td>
                <td>
                    <p class="name">
                        {% if (file.url) { %}
                        {% } else { %}
                            <span>{%=file.name%}</span>
                        {% } %}
                    </p>
                    {% if (file.error) { %}
                        <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                    {% } %}
                </td>
                <td>
                    {% if (file.deleteUrl) { %}
                        <button class="btn red delete btn-sm" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                            <i class="fa fa-trash-o"></i>
                            <span>Delete</span>
                        </button>
                    {% } else { %}
                        <button class="btn yellow cancel btn-sm">
                            <i class="fa fa-ban"></i>
                            <span>Cancel</span>
                        </button>
                    {% } %}
                </td>
            </tr>
        {% } %}
    </script>
    <script src="/assetsx/global/plugins/fancybox/source/jquery.fancybox.pack.js?32123"></script>
    <!-- END PAGE LEVEL PLUGINS-->
    <!-- BEGIN:File Upload Plugin JS files-->
    <!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js?32123"></script>
    <!-- The Templates plugin is included to render the upload/download listings -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/vendor/tmpl.min.js?32123"></script>
    <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/vendor/load-image.min.js?32123"></script>
    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/vendor/canvas-to-blob.min.js?32123"></script>
    <!-- blueimp Gallery script -->
    <script src="/assetsx/global/plugins/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js?32123"></script>
    <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.iframe-transport.js?32123"></script>
    <!-- The basic File Upload plugin -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.fileupload.js?32123"></script>
    <!-- The File Upload processing plugin -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.fileupload-process.js?32123"></script>
    <!-- The File Upload image preview & resize plugin -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.fileupload-image.js?32123"></script>
    <!-- The File Upload audio preview plugin -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.fileupload-audio.js?32123"></script>
    <!-- The File Upload video preview plugin -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.fileupload-video.js?32123"></script>
    <!-- The File Upload validation plugin -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.fileupload-validate.js?32123"></script>
    <!-- The File Upload user interface plugin -->
    <script src="/assetsx/global/plugins/jquery-file-upload/js/jquery.fileupload-ui.js?32123"></script>
    <!-- The main application script -->
    <!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
    <!--[if (gte IE 8)&(lt IE 10)]>
    <script src="/assetsx/global/plugins/jquery-file-upload/js/cors/jquery.xdr-transport.js?32123"></script>
    <![endif]-->
    <!-- END:File Upload Plugin JS files-->
    <script src="/assetsx/global/scripts/metronic.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/layout.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/quick-sidebar.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/demo.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/pages/scripts/form-fileupload.js?32123"></script>
    <script>
        jQuery(document).ready(function() {
            Metronic.init(); // init metronic core components
            Layout.init(); // init current layout
            QuickSidebar.init(); // init quick sidebar
            FormFileUpload.init();
        });
    </script>
<?php elseif(in_array($controller, ["countries", "parameters"]) && in_array($action, ["index"])): ?>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/global/scripts/metronic.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/layout.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/demo.js?32123" type="text/javascript"></script>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/global/plugins/jstree/dist/jstree.min.js?2"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/admin/pages/scripts/ui-tree.js?32123"></script>
    <script>
        $(document).ready(function()
        {
            $('#clickmewow').click(function()
            {
                $('#radio1003').attr('checked', 'checked');
            });
        })

        jQuery(document).ready(function(){
            $(".input-car-index").keyup(function(){
                var catId = $(this).attr("cat_id");
                //alert( "<?=_ROOT_;?>/categories/setindex/"+catId+"?index_id="+$(this).val());
                var jqxhr = $.ajax("<?=_ROOT_;?>/<?=$controller;?>/setindex/"+catId+"?index_id="+$(this).val())
                    .done(function() {
                    })
            });
            $(".input-car-active").click(function(){
                var catId = $(this).attr("cat_id");
                //alert( "<?=_ROOT_;?>/categories/setindex/"+catId+"?index_id="+$(this).val());
                var jqxhr = $.ajax("<?=_ROOT_;?>/<?=$controller;?>/setvisible/"+catId+"?status="+($(this).is(':checked') ? 1: 0))
                    .done(function() {
                    })
            });
        });

        function setCatIndex(carId, indexId){

        }
    </script>
<?php else: ?>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assetsx/global/scripts/metronic.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/layout.js?32123" type="text/javascript"></script>
    <script src="/assetsx/admin/layout/scripts/demo.js?32123" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function() {
            Metronic.init(); // init metronic core componets
            Layout.init(); // init layout
        });
    </script>
<?php endif;?>
<!-- END PAGE LEVEL SCRIPTS -->
