<!DOCTYPE html>
<html lang="en" >
<!-- begin::Head -->
<head>
    <meta charset="utf-8" />
    <title>
        <?=$this->lang->get("siteTitle", "CareCompagniet");?> - <?=$this->lang->get("Login", "Log ind");?>
    </title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--end::Web font -->
    <!--begin::Base Styles -->
    <link href="/cc-crm2/assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />
    <link href="/cc-crm2/assets/demo/default/base/style.bundle.css" rel="stylesheet" type="text/css" />
    <!--end::Base Styles -->
    <link rel="shortcut icon" href="/cc-crm2/assets/demo/default/media/img/logo/favicon.ico" />
</head>
<!-- end::Head -->
<!-- end::Body -->
<body  class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default"  >
<!-- begin:: Page -->
<div class="m-grid m-grid--hor m-grid--root m-page">
    <div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-grid--tablet-and-mobile m-grid--hor-tablet-and-mobile m-login m-login--1 m-login--signin" id="m_login">
        <div class="m-grid__item m-grid__item--order-tablet-and-mobile-2 m-login__aside">
            <div class="m-stack m-stack--hor m-stack--desktop">
                <div class="m-stack__item m-stack__item--fluid">
                    <div class="m-login__wrapper">
                        <div class="m-login__logo">
                            <a href="#">
                                <img src="http://placehold.it/96x65">
                            </a>
                        </div>
                        <div class="m-login__signin">
                            <div class="m-login__head">
                                <h3 class="m-login__title">
                                    <?=$this->lang->get("Login", "Log ind");?>
                                </h3>
                            </div>
                            <form class="m-login__form m-form" action="" method="post">
                                <div class="form-group m-form__group row">
                                    <style>
                                        .form-error,.form-success{
                                            display: block;
                                            width: 100%;
                                            font-size: 14px;
                                            font-weight: normal;
                                            text-align: left;
                                            border-radius: 4px;
                                            background-color: #f3cdd3;
                                            color: #210406;
                                            margin: 0 0 20px 0;
                                            padding: 12px 12px 12px 12px;
                                            border-left: 4px solid #de6c6c;
                                        }
                                    </style>
                                    <div class="form-error" id="error_alert" style="display: none;">

                                    </div>
                                </div>
                                <div class="form-group m-form__group">
                                    <input class="form-control m-input" type="text" placeholder="<?=$this->lang->get("Username");?>" name="username" autocomplete="off" value="<?=$this->request->get("username");?>">
                                </div>
                                <div class="form-group m-form__group">
                                    <input class="form-control m-input m-login__form-input--last" type="password" placeholder="<?=$this->lang->get("Password");?>" name="password">
                                </div>
                                <div class="row m-login__form-sub">
                                    <div class="col m--align-left">
                                        <label class="m-checkbox m-checkbox--focus">
                                            <input type="checkbox" name="remember" value="1">
                                            <?=$this->lang->get("RememberMe", "Husk mig");?>
                                            <span></span>
                                        </label>
                                    </div>
                                    <!--
                                    <div class="col m--align-right">
                                        <a href="javascript:;" id="m_login_forget_password" class="m-link">
                                            Glemt dit kodeord?
                                        </a>
                                    </div> -->
                                </div>
                                <div class="m-login__form-action">
                                    <button id="m_login_signin_submit" class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air">
                                        <?=$this->lang->get("Login");?>
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div class="m-login__forget-password">
                            <div class="m-login__head">
                                <h3 class="m-login__title">
                                    Glemt dit kodeord?
                                </h3>
                                <div class="m-login__desc">
                                    Skriv din e-mail adresse for at gendanne dit kodeord
                                </div>
                            </div>
                            <form class="m-login__form m-form" action="">
                                <div class="form-group m-form__group">
                                    <input class="form-control m-input" type="text" placeholder="E-mail Adresse" name="email" id="m_email" autocomplete="off">
                                </div>
                                <div class="m-login__form-action">
                                    <button id="m_login_forget_password_submit" class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air">
                                        Gendan
                                    </button>
                                    <button id="m_login_forget_password_cancel" class="btn btn-outline-focus m-btn m-btn--pill m-btn--custom">
                                        Annueler
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>

                    <style>
                        .btn-lang{background: #e1e1e1;border: 1px solid #d5d5d5;border-radius: 15px;padding: 8px 10px;color: #444;font-size: 15px;}
                    </style>
                    <div style="display: block;text-align: center;">
                        <?php foreach($this->lang->langs as $value):?>
                            <a href="?_setlang=<?=$value;?>" class="btn-lang" style="margin-right: 10px;"><?=$value;?></a>
                        <?php endforeach;?>
                    </div>
                </div>
            </div>
        </div>
        <div class="m-grid__item m-grid__item--fluid m-grid m-grid--center m-grid--hor m-grid__item--order-tablet-and-mobile-1	m-login__content" style="background-image: url(/cc-crm2/assets/app/media/img//bg/bg-4.jpg)">
            <div class="m-grid__item m-grid__item--middle">
                <h3 class="m-login__welcome">
                    <?=$this->lang->get("siteTitle", "CareCompagniet");?>
                </h3>
                <p class="m-login__msg">
                    <?=$this->lang->get("siteDescription", "Lorem ipsum dolor sit amet, coectetuer adipiscing elit sed diam nonummy et nibh euismod");?>
                </p>
            </div>
        </div>
    </div>
</div>

<script>
    var datePickerSettings = {
        en: {
            days:["Søndag", "Mandag", "Tirsdag", "Onsdag", "Torsdag", "Fredag", "Lørdag"],
            daysShort:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],
            daysMin:["Sø", "Ma", "Ti", "On", "To", "Fr", "Lø"],
            months:["<?=$this->lang->get("January");?>","<?=$this->lang->get("February");?>","<?=$this->lang->get("March");?>","<?=$this->lang->get("April");?>","<?=$this->lang->get("May");?>","<?=$this->lang->get("June");?>","<?=$this->lang->get("July");?>","<?=$this->lang->get("August");?>","<?=$this->lang->get("September");?>","<?=$this->lang->get("October");?>","<?=$this->lang->get("November");?>","<?=$this->lang->get("December");?>"],
            monthsShort:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
            today:"Today",clear:"Clear",titleFormat:"MM yyyy"
        }
    };
</script>

<!-- end:: Page -->
<!--begin::Base Scripts -->
<script src="/cc-crm2/assets/vendors/base/vendors.bundle.js" type="text/javascript"></script>
<script src="/cc-crm2/assets/demo/default/base/scripts.bundle.js" type="text/javascript"></script>
<!--end::Base Scripts -->
<!--begin::Page Snippets -->
<script src="/resources/js/login.js?<?=rand(1,999999999);?>" type="text/javascript"></script>
<!--end::Page Snippets -->
</body>
<!-- end::Body -->
</html>
