<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?=$this->lang->get("CreateNew", "Opret ny");?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Todo");?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/add" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("CreateNew", "Opret ny");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("CreateNew", "Opret ny");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else:?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("DateStart", "Start Date");?></label>
                        <div class="col-7">
                            <input class="form-control m-input datepickerDen" name="date_start" type="text" value="<?=(($this->request->get("date_start")) ? $this->request->get("date_start"): $this->lib->dateToDanish(date("Y-m-d")));?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("TimeStart", "Start Time");?></label>
                        <div class="col-7">
                            <input class="form-control m-input timepicker" name="time_start" type="text" value="<?=$this->request->get("time_start");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Place");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="place_start" type="text" value="<?=$this->request->get("place_start");?>">
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("DateSEnd", "End Date");?></label>
                        <div class="col-7">
                            <input class="form-control m-input datepickerDen" name="date_end" type="text" value="<?=(($this->request->get("date_end")) ? $this->request->get("date_end"): $this->lib->dateToDanish(date("Y-m-d")));?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("TimeEnd", "Start End");?></label>
                        <div class="col-7">
                            <input class="form-control m-input timepicker2" name="time_end" type="text" value="<?=$this->request->get("time_end");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Place");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="place_end" type="text" value="<?=$this->request->get("place_end");?>">
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("CaseNumber", "Case number");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="case" type="text" value="<?=$this->request->get("case");?>" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("AssociateCitizen", "Tilknyt borger");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_1" name="citizen">
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($citizens as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((int)$value->id == (int)$this->request->get("citizen") ? 'selected="selected"': '');?>><?=$value->firstname;?> <?=$value->lastname;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("AssociateEmployee", "Tilknyt medarbejder");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_2" name="employee">
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($employees as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((int)$value->id == (int)$this->request->get("employee") ? 'selected="selected"': '');?>><?=$value->firstname;?> <?=$value->lastname;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-7">
                            <?php if($success):?>
                                <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                            <?php else:?>
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            <?php endif?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>

<link href="/resources/css/wickedpicker.css" rel="stylesheet" type="text/css"/>

