<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?=$this->lang->get("Todo");?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Partners");?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/edit/<?=$data->id;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Edit", "Edit");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("Edit", "Edit");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else:?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Title");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="title" type="text" value="<?=htmlspecialchars($data->title);?>" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Category");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_3" name="category[]" multiple="multiple">
                                <optgroup label="">
                                    <?php foreach($this->parameters->getList($this->lang, "todo_categories") as $value):?>
                                        <option value="<?=(int)$value["id"];?>" <?=((in_array((int)$value["id"], $data->category)) ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                    <?php endforeach;?>
                                </optgroup>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Description");?></label>
                        <div class="col-7">
                            <textarea class="form-control" name="description" style="min-height: 200px;"><?=htmlspecialchars($data->description);?></textarea>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("CaseNumber", "Case number");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="case" type="text" value="<?=htmlspecialchars($data->case);?>" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("AssociateCitizen", "Tilknyt borger");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_1" name="citizen">
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($citizens as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((int)$value->id == (int)$data->citizen ? 'selected="selected"': '');?>><?=htmlspecialchars($value->firstname);?> <?=htmlspecialchars($value->lastname);?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("AssociateEmployee", "Tilknyt medarbejder");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_2" name="employee">
                                <option value="0"><?=$this->lang->get("None");?></option>
                                <?php foreach($employees as $value):?>
                                    <option value="<?=(int)$value->id;?>" <?=((int)$value->id == (int)$data->employee ? 'selected="selected"': '');?>><?=htmlspecialchars($value->firstname);?> <?=htmlspecialchars($value->lastname);?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Color");?></label>
                        <div class="col-7">
                            <select class="form-control m-select2" id="m_select2_5" name="color">
                                <?php foreach($this->parameters->getList($this->lang, "colors") as $value):?>
                                    <option value="<?=(int)$value["id"];?>" <?=((int)$value["id"] == $data->color ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Date");?></label>
                        <div class="col-7">
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" class="form-control" name="date" value="<?=$data->date->toDateTime()->format("m/d/Y");?>" autocomplete="off">
                                <div class="input-group-addon">
                                    <span class="glyphicon glyphicon-th"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-7">
                            <?php if($success):?>
                                <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                            <?php else:?>
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            <?php endif?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>