<section id="registration_citizen">
    <h2 id="html-structure"><a href="javascript:;"> Authentication / Registration for Citizen</a></h2>
    <div class="div-body">
        <div class="param-title"><b>Url:</b> <?=API_ROOT;?>/register/citizen</div>
        <div class="param-title"><b>Methods:</b> <code>POST/GET</code></div>
        <div class="param-title"><b>Request params:</b></div>
        <div class="div-params bg-gray padding-left-offset">
            <code>lang:</code> (type: STRING: en/da)<br/>
            <code>firstname:</code> (type: STRING)<br/>
            <code>lastname:</code> (type: STRING)<br/>
            <code>password:</code> (type: STRING)<br/>
            <code>phone:</code>  (type: STRING, format: +380731033735)<br/>
            <code>email:</code> (type: STRING)<br/>
            <code>ssn:</code> (type: STRING)<br/>
            <code>place:</code> (type: STRING)<br/>
            <code>address:</code> (type: STRING)<br/>
            <code>zipcode:</code> (type: STRING)<br/>
            <code>city:</code> (type: INT) <a href="#data_cities">get city list here</a><br/>
        </div>
        <div class="param-title"><b>Response:</i> (success)</b></div>
        <div class="div-params bg-gray padding-left-offset">
            <b>Example</b>: <?=SITE_URL;?><?=API_ROOT;?>/register/citizen?firstname=Testing&lastname=Testing&password=123456&phone=+380731033735&email=test@test.com&ssn=12346&place=Denmark&address=Streat+test+12&zipcode=10000&city=1<br/>
            <?php
            $json = '{"status":"success","description":"Added successfully","token":"4a65bf42eebb7e0d0c59ec786d17edd3","hash":"72f798a12ecc44b184ee9c890566ca3c","data":{"id":11,"firstname":"Testing","lastname":"Testing","phone":"380731033736","email":"test@test.com","ssn":"12346","place":"Denmark","address":"Streat test 12","zipcode":"10000","city":1,"type":"citizen"}}' ;
            ?>
            <pre><?=$this->lib->jsonPrettyPrint($json);?></pre>
        </div>
        <div class="param-title"><b>Response:</i> (error)</b></div>
        <div class="div-params bg-gray padding-left-offset">
            <b>Example</b>: <?=SITE_URL;?><?=API_ROOT;?>/register/citizen?firstname=Testing&lastname=Testing&password=123456&phone=+380731033735&email=test@test.com&ssn=12346&place=Denmark&address=Streat+test+12&zipcode=10000&city=1<br/>
            <?php
            $json = '{"status":"error","error_code":1101,"description":"User exists"}';
            ?>
            <pre><?=$this->lib->jsonPrettyPrint($json);?></pre>
        </div>
    </div>
</section>
