<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?=$this->lang->get("NewCitizen", "Ny Borger");?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/citizens" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Citizens");?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/citizens" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("NewCitizen", "Ny Borger");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("NewCitizen", "Ny Borger");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else:?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="form-group m-form__group row">
                        <div class="col-10 ml-auto">
                            <h3 class="m-form__section">1. <?=$this->lang->get("PersonalInformation", "Personlige Oplysninger");?></h3>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Firstname", "Fornavn");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="firstname" type="text" value="<?=$this->request->get("firstname");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Lastname", "Efternavn");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="lastname" type="text" value="<?=$this->request->get("lastname");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Email", "E-mail Adresse");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="email" type="text" value="<?=$this->request->get("email");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("SocialSecurityNumber", "CPR-nummer");?></label>
                        <div class="col-7">
                            <input id="ssnnumber" class="form-control m-input" name="ssn" type="text" value="<?=$this->request->get("ssn");?>" placeholder="DDMMYY-XXXX">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("PhoneNumber", "Telefonnummer");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="phone" type="text" value="<?=$this->request->get("phone");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Password");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="password" type="text" value="<?=$this->request->get("password");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("School", "Skole");?> / <?=$this->lang->get("Kindergarden", "Børnehave");?> / <?=$this->lang->get("Institution", "Institution");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="place" type="text" value="<?=$this->request->get("place");?>">
                        </div>
                    </div>

                    <div class="m-form__seperator m-form__seperator--dashed m-form__seperator--space-2x"></div>

                    <div class="form-group m-form__group row">
                        <div class="col-10 ml-auto">
                            <h3 class="m-form__section">2. <?=$this->lang->get("Address", "Adresse");?></h3>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Address", "Adresse");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="address" type="text" value="<?=$this->request->get("address");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("ZipCode", "Postnummer");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="zipcode" type="text" value="<?=$this->request->get("zipcode");?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("City", "By");?></label>
                        <div class="col-7">
                            <select class="form-control m-input" name="city">
                                <?php foreach($this->parameters->getList($this->lang, "cities") as $value):?>
                                    <option value="<?=(int)$value["id"];?>" <?=((int)$value["id"] == (int)$this->request->get("city") ? 'selected="selected"': '');?>><?=$value["title"];?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-7">
                            <?php if($success):?>
                                <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                            <?php else:?>
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            <?php endif?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>