<div class="m-portlet m-portlet--full-height m-portlet--tabs  ">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                        <i class="flaticon-share m--hide"></i>
                        <?=$this->lang->get("UserProfile", "Profile");?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-pane active" id="m_user_profile_tab_1">
            <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
                <div class="m-portlet__body">
                    <?php if($success):?>
                        <div class="form-group m-form__group row">
                            <div class="form-success">
                                <?=$success;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="form-group m-form__group row">
                        <div class="col-9 ml-auto">
                            <h3 class="m-form__section">1. <?=$this->lang->get("PersonalInformation", "Personlige Oplysninger");?></h3>
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Firstname", "Fornavn");?></label>
                        <div class="col-7">
                            <!--<input class="form-control m-input" name="firstname" type="text" value="<?=htmlspecialchars($data->firstname);?>" readonly="readonly" disabled/> -->
                            <div class="profile-info-right"><?=htmlspecialchars($data->firstname);?></div>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Lastname", "Efternavn");?></label>
                        <div class="col-7">
                            <!-- <input class="form-control m-input" name="lastname" type="text" value="<?=htmlspecialchars($data->lastname);?>" readonly="readonly" disabled> -->
                            <div class="profile-info-right"><?=htmlspecialchars($data->lastname);?></div>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("PhoneNumber", "Telefonnummer");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="phone" type="text" value="<?=htmlspecialchars($data->phone);?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Email", "E-mail Adresse");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="email" type="text" value="<?=htmlspecialchars($data->email);?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Gender", "Køn");?></label>
                        <div class="col-7">
                            <select class="form-control m-input" name="gender">
                                <option value=""><?=$this->lang->get("Choose");?></option>
                                <option value="male" <?=($data->gender == "male" ? 'selected="selected"': '');?>><?=$this->lang->get("Male", "Mand");?></option>
                                <option value="female" <?=($data->gender == "female" ? 'selected="selected"': '');?>><?=$this->lang->get("Female", "Kvinde");?></option>
                            </select>
                        </div>
                    </div>

                    <?php if(in_array($data->type, ["employee", "citizen"])):?>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("SocialSecurityNumber", "CPR-nummer");?></label>
                            <div class="col-7">
                                <input id="ssnnumber" class="form-control m-input" name="ssn" type="text" value="<?=htmlspecialchars($data->ssn);?>" readonly="readonly" disabled/>
                            </div>
                        </div>
                        <?php if(in_array($data->type, ["citizen"])):?>
                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("School", "Skole");?> / <?=$this->lang->get("Kindergarden", "Børnehave");?> / <?=$this->lang->get("Institution", "Institution");?></label>
                                <div class="col-7">
                                    <input class="form-control m-input" name="place" type="text" value="<?=htmlspecialchars($data->place);?>" readonly="readonly" disabled/>
                                </div>
                            </div>
                        <?php endif;?>
                        <?php if(in_array($data->type, ["employee"])):?>
                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("EndDate");?></label>
                                <div class="col-7">
                                    <div class="input-group ">
                                        <input type="text" class="form-control datepicker"  name="end_date" value="<?=$this->lib->dateToDanish($this->mymongo->dateFormat($data->end_date, "Y-m-d"));?>" autocomplete="off" readonly="readonly" disabled>
                                        <div class="input-group-addon">
                                            <span class="glyphicon glyphicon-th"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endif;?>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("LanguageProficiency", "Sprogkundskaber");?></label>
                            <div class="col-7">
                                <select class="form-control m-select2" id="m_select2_3" name="languages[]" multiple="multiple">
                                    <optgroup label="<?=$this->lang->get("Language", "Sprog");?>">
                                        <?php foreach($this->parameters->getList($this->lang, "languages") as $value):?>
                                            <option value="<?=(int)$value["id"];?>" <?=((in_array((int)$value["id"], $data->languages)) ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                        <?php endforeach;?>
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                    <?php endif;?>


                    <div class="m-form__seperator m-form__seperator--dashed m-form__seperator--space-2x"></div>

                    <div class="form-group m-form__group row">
                        <div class="col-9 ml-auto">
                            <h3 class="m-form__section">2. <?=$this->lang->get("Address", "Adresse");?></h3>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("City", "By");?></label>
                        <div class="col-7">
                            <select class="form-control m-input" name="city">
                                <?php foreach($this->parameters->getList($this->lang, "cities") as $value):?>
                                    <option value="<?=(int)$value["id"];?>" <?=((int)$value["id"] == (int)$data->city ? 'selected="selected"': '');?>><?=htmlspecialchars($value["title"]);?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("Address", "Adresse");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="address" type="text" value="<?=htmlspecialchars($data->address);?>">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("ZipCode", "Postnummer");?></label>
                        <div class="col-7">
                            <input class="form-control m-input" name="zipcode" type="text" value="<?=htmlspecialchars($data->zipcode);?>">
                        </div>
                    </div>




                    <?php if(in_array($data->type, ["employee"])):?>
                        <div class="m-form__seperator m-form__seperator--dashed m-form__seperator--space-2x"></div>

                        <div class="form-group m-form__group row">
                            <div class="col-9 ml-auto">
                                <h3 class="m-form__section">3. <?=$this->lang->get("PaymentDetails", "Betalingsoplysninger");?></h3>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("RegistrationNumber", "Registrerings nr.");?></label>
                            <div class="col-7">
                                <input class="form-control m-input" name="payment_registration_number" type="text" value="<?=htmlspecialchars($data->payment_registration_number);?>">
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-3 col-form-label"><?=$this->lang->get("AccountNumber", "Konto nr.");?></label>
                            <div class="col-7">
                                <input class="form-control m-input" name="payment_account_number" type="text" value="<?=htmlspecialchars($data->payment_account_number);?>">
                            </div>
                        </div>
                    <?php endif;?>
                </div>
                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <div class="row">
                            <div class="col-3">
                            </div>
                            <div class="col-7">
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="tab-pane " id="m_user_profile_tab_2">

        </div>
        <div class="tab-pane " id="m_user_profile_tab_3">

        </div>
    </div>
</div>