<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?=$this->lang->get("Edit");?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Moderators");?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/edit/<?=$data->id;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Edit", "Edit");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("Edit", "Edit");?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php endif;?>
                <?php if($error):?>
                    <div class="form-group m-form__group row">
                        <div class="form-error">
                            <?=$error;?>
                        </div>
                    </div>
                <?php endif;?>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Username");?></label>
                    <div class="col-7">
                        <input class="form-control m-input" name="mod_username" type="text" value="<?=htmlspecialchars($data->username);?>">
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Password");?></label>
                    <div class="col-7">
                        <input class="form-control m-input" name="password" type="text" value="" placeholder="******">
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Firstname", "Fornavn");?></label>
                    <div class="col-7">
                        <input class="form-control m-input" name="firstname" type="text" value="<?=htmlspecialchars($data->firstname);?>">
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Lastname", "Efternavn");?></label>
                    <div class="col-7">
                        <input class="form-control m-input" name="lastname" type="text" value="<?=htmlspecialchars($data->lastname);?>">
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("PhoneNumber", "Telefonnummer");?></label>
                    <div class="col-7">
                        <input class="form-control m-input" name="phone" type="text" value="<?=htmlspecialchars($data->phone);?>">
                    </div>
                </div>

                <style>
                    .option-item{width: 100%;display: table;padding: 8px 10px;background: #f1f1f1;text-decoration: none;color: #a1a1a1;border-bottom: 1px solid white;text-decoration: none !important;cursor: default !important;}
                    .option-item-hover:hover{background: #e7e7e7;color: #a1a1a1;cursor: pointer !important;}
                    .option-checkbox, .option-price, .option-title{display: table-cell;}
                    .option-checkbox{width: 25px;text-decoration: none;}
                    .option-title{text-decoration: none;color: #444;}
                    .fa-gray{color: #aeaeae !important;}
                    .fa-green{color: green !important;}
                    .permission-type{padding: 0 !important;border-right: 1px solid white;}
                    .permission-title{padding: 9px 10px 0 5px;text-align: right;background: #e1e1e1;height: 35px;border-right: 1px solid white;}
                    .permission-btn{padding: 8px 20px;border: 1px solid #e1e1e1;border-radius: 3px;background: #e1e1e1;color: #444;font-size: 14px;text-decoration: none;margin-right: 10px;}
                    .permission-btn:hover{border: 1px solid #d1d1d1;border-radius: 3px;background: #d4d4d4;text-decoration: none;}
                </style>
                <script>
                    var permissionsList = <?=json_encode($this->permission->getList($this->lang), true);?>;
                    var userPermissions = <?=(count($data->permissions) == 0 || !$data->permissions ? '{}': json_encode($data->permissions, true));?>;
                </script>
                <div class="form-group m-form__group row">
                    <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Permissions");?></label>
                    <div class="col-10">
                        <div style="padding-bottom: 30px;">
                            <input id="only_self" style="width: 30px;float: left;margin-top: 5px;" class="form-control m-input" name="only_self" type="checkbox" value="1" <?=((int)$data->only_self == 1 ? 'checked="checked"': '');?> onchange="selfEditChanged()"> <span><?=$this->lang->get("OnlySelfEdit", "Can edit only his/her information");?></span>
                        </div>
                        <div id="permission_container" <?=((int)$data->only_self == 1 ? 'style="display: none;"': '');?>>
                            <div style="padding-bottom: 15px;">
                                <a href="javascript:PPermission.checkAll();" class="permission-btn"><?=$this->lang->get("SelectAll", "Select all");?></a>
                                <a href="javascript:PPermission.uncheckAll();" class="permission-btn"><?=$this->lang->get("UnselectAll", "Unselect All");?></a>
                            </div>
                            <div class="col-sm-12" id="permissions_list" style=""></div>
                        </div>
                        <input id="hidden_permissions" type="hidden" name="permissions" value='<?=(count($data->permissions) == 0 || !$data->permissions ? '{}': json_encode($data->permissions, true));?>'/>
                    </div>
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-7">
                            <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save", "Gem ændringer");?></button>&nbsp;&nbsp;
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>
<script>
    function selfEditChanged(){
        var obj = document.getElementById("permission_container");
        if(document.getElementById("only_self").checked)
        {
            obj.style.display = 'none';
        }
        else
        {
            obj.style.display = 'block';
        }
    }
</script>