<div class="m-subheader ">
    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-default"><i class="la la-arrow-left"></i> <?=$this->lang->get("Back");?></a>
</div>

<div class="m-content">
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("Documents");?>
                    </h3>
                </div>
            </div>
        </div>
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if(count($documents) == 0):?>
                    <div class="form-group m-form__group row">
                        <div class="form-error">
                            <?=$this->lang->get("NotFoundDocument", "Document not found");?>
                        </div>
                    </div>
                <?php endif;?>
                <?php foreach($documents as $key => $value):?>
                    <div class="form-group m-form__group row">
                        <div class="col-5" style="width: 30px;">
                            <b><?=$key+1;?>)
                            <?php if($value->folder > 0):?>
                                <?=htmlspecialchars($vacancyFolders[$value->folder]["title"]);?>
                            <?php else:?>

                            <?php endif;?>
                            </b>
                        </div>

                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-2">
                            <?php if(in_array($value->type, array("jpeg", "jpg", "png", "gif"))): ?>
                                <a target="_blank" href="/upload/<?=(string)$value->uuid;?>/<?=(string)$value->_id;?>/org.jpg">
                                    <img style="max-width: 100%;" src="/upload/<?=(string)$value->uuid;?>/<?=(string)$value->_id;?>/small.jpg"/>
                                </a>
                            <?php else: ?>
                                <a target="_blank" href="/upload/<?=(string)$value->uuid;?>/<?=(string)$value->_id;?>/<?=(string)htmlspecialchars($value->filename).'.'.$value->type;?>"><b><?=(string)htmlspecialchars($value->filename).'.'.$value->type;?></b></a>
                            <?php endif;?>
                        </div>
                        <div class="col-1">
                            <a href="?delete=<?=(string)$value->_id;?>"><i class="la la-trash redcolor"></i></a>
                        </div>
                    </div>
                    <hr/>
                <?php endforeach;?>
            </div>
        </form>
    </div>
</div>

<div class="m-content">
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?=$this->lang->get("Upload");?>
                    </h3>
                </div>
            </div>
        </div>
        <form class="m-form m-form--fit m-form--label-align-right" method="post" action="">
            <div class="m-portlet__body">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else:?>
                    <?php if($error):?>
                        <div class="form-group m-form__group row">
                            <div class="form-error">
                                <?=$error;?>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="form-group m-form__group row">
                        <label for="example-text-input" class="col-2 col-form-label"><?=$this->lang->get("Folder");?></label>
                        <div class="col-5">
                            <select name="folder" class="form-control form-filter input-sm">
                                <option value=""><?=$this->lang->get("Select");?></option>
                                <?php foreach($vacancyFolders as $value):?>
                                    <option value="<?=$value["id"];?>"><?=htmlspecialchars($value["title"]);?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-7">
                            <div class="m-dropzone dropzone dz-clickable" action="/documents/upload?puid=<?=$puid;?>" id="m-dropzone-one">
                                <div class="m-dropzone__msg dz-message needsclick">
                                    <h3 class="m-dropzone__msg-title"><?=$this->lang->get("CaseMatL1", "Drop filen her eller tryk for at vælge");?></h3>
                                    <span class="m-dropzone__msg-desc"><?=$this->lang->get("CaseMatL2", "Kun tilladt at upload billede eller pdf, docx og xlsx filer");?></span>
                                </div>
                            </div>
                            <input type="hidden" name="puid" value="<?=$puid;?>"/>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-7">
                            <?php if($success):?>
                                <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="btn btn-accent m-btn m-btn--air m-btn--custom"><?=$this->lang->get("Back");?></a>&nbsp;&nbsp;
                            <?php else:?>
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save");?></button>&nbsp;&nbsp;
                            <?php endif?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


