<script>
    var tablelisturl = '<?=_PANEL_ROOT_;?>/<?=$controller;?>/list';
</script>
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?=$this->lang->get("Vacancies");?>
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<?=_PANEL_ROOT_;?>" class="m-nav__link m-nav__link--icon"><i class="m-nav__link-icon la la-home"></i></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Vacancies");?></span></a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>" class="m-nav__link"><span class="m-nav__link-text"><?=$this->lang->get("Overview");?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__body">
            <?php //if($this->auth->isPermitted($controller, "add")):?>
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1"></div>
                        <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                            <a href="<?=_PANEL_ROOT_;?>/<?=$controller;?>/edit/0" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill"><span><i class="la la-user-plus"></i><span><?=$this->lang->get("CreateNew", "Opret ny");?></span></span></a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>
            <?php //endif;?>
            <!--begin: Datatable -->
            <div class="table-container">
                <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                    <thead>
                    <div class="table-actions-wrapper">
                        <span></span>
                        <select class="table-group-action-input form-control input-inline input-small input-sm">
                            <option value="false"><?=$this->lang->get("Select");?></option>
                            <option value="block"><?=$this->lang->get("Block");?></option>
                            <option value="unblock"><?=$this->lang->get("Unblock");?></option>
                            <option value="">-------</option>
                            <option value="delete"><?=$this->lang->get("Delete");?></option>
                        </select>
                        <button class="btn btn-sm yellow table-group-action-submit"><i class="fa fa-check"></i> <?=$this->lang->get("Execute");?></button>
                    </div>

                    <tr role="row" class="heading">
                        <th width="2%"><input type="checkbox" class="group-checkable"></th>
                        <th><?=$this->lang->get("Info");?></th>
                        <th><?=$this->lang->get("Gender");?></th>
                        <th><?=$this->lang->get("Age");?></th>
                        <th><?=$this->lang->get("Language");?></th>
                        <th><?=$this->lang->get("Education");?> / <?=$this->lang->get("occupation", "Occupation");?></th>
                        <th><?=$this->lang->get("work_experience", "Work experience");?></th>
                        <th></th>
                    </tr>
                    <tr role="row" class="filter">
                        <td colspan="7">
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="title" autocomplete="off" placeholder="Fullname">
                                </div>
                                <div class="col-sm-4">
                                    <select name="gender" class="form-control form-filter input-sm">
                                        <option value=""><?=$this->lang->get("Gender");?></option>
                                        <option value="male"><?=$this->lang->get("Male");?></option>
                                        <option value="female"><?=$this->lang->get("Female");?></option>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="address" autocomplete="off" placeholder="<?=$this->lang->get("Address");?>">
                                </div>
                            </div>
                            <div class="row" style="margin-top: 10px;">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="email" autocomplete="off" placeholder="<?=$this->lang->get("Email");?>">
                                </div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="phone" autocomplete="off" placeholder="<?=$this->lang->get("Phone");?>">
                                </div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="work_position" autocomplete="off" placeholder="<?=$this->lang->get("WorkPosition");?>">
                                </div>
                            </div>


                            <div class="row" style="margin-top: 10px;">
                                <div class="col-sm-4">
                                    <select class="form-control form-filter input-sm" name="city">
                                        <option value=""><?=$this->lang->get("City");?></option>
                                        <?php foreach($this->parameters->getList($this->lang, "vacancy_cities") as $value):?>
                                            <option value="<?=(int)$value["id"];?>" <?=((int)$value["id"] == (int)$data->city ? 'selected="selected"': '');?>><?=$value["title"];?></option>
                                        <?php endforeach;?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="post_number" autocomplete="off" placeholder="<?=$this->lang->get("ZipCode");?>">
                                </div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="work_experience" autocomplete="off" placeholder="<?=$this->lang->get("work_experience");?>">
                                </div>
                            </div>


                            <div class="row" style="margin-top: 10px;">
                                <div class="col-sm-4">
                                    <select class="form-control form-filter input-sm" name="language">
                                        <option value=""><?=$this->lang->get("Language");?></option>
                                        <?php foreach($this->parameters->getList($this->lang, "vacancy_languages") as $value):?>
                                            <option value="<?=(int)$value["id"];?>" <?=((in_array((int)$value["id"], $data->languages)) ? 'selected="selected"': '');?>><?=$value["title"];?></option>
                                        <?php endforeach;?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-filter input-sm search-input" name="occupation" autocomplete="off" placeholder="<?=$this->lang->get("occupation");?>">
                                </div>
                            </div>


                            <div class="row" style="margin-top: 10px;">
                                <?php foreach($vacancySwitches as $value):?>
                                <div class="col-4">
                                    <label class="m-checkbox">
                                        <input class="form-filter" type="checkbox" name="<?=$value["name"];?>" value="1"/> <?=$value["title"];?>
                                        <span></span>
                                    </label>
                                </div>
                                <?php endforeach;?>
                            </div>


                            <!--
                            <div class="row" style="margin-top: 10px;">
                                <select class="form-control form-filter m-select2" id="m_select2_2" name="options[]" multiple="multiple">
                                    <optgroup label="<?=$this->lang->get("Options");?>">
                                        <?php foreach($vacancySwitches as $value):?>
                                            <option value="<?=(int)$value["id"];?>" <?=((in_array((int)$value["id"], $data->languages)) ? 'selected="selected"': '');?>><?=$value["title"];?></option>
                                        <?php endforeach;?>
                                    </optgroup>
                                </select>
                            </div> -->


                        </td>
                        <td>
                            <div class="margin-bottom-5" style="margin-bottom: 6px;">
                                <button class="btn btn-sm yellow filter-submit"><i class="fa fa-search"></i> <?=$this->lang->get("Search");?></button>
                            </div>
                            <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> <?=$this->lang->get("Reset");?></button>
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <!--end: Datatable -->
        </div>
    </div>
</div>