<html>
<head>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>
    <!--end::Web font -->
    <!--begin::Base Styles -->
    <!--begin::Page Vendors -->
    <link href="/cc-crm2/assets/vendors/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css" />
    <!--end::Page Vendors -->
    <link href="/cc-crm2/assets/vendors/base/vendors.bundle.css?1s" rel="stylesheet" type="text/css" />
    <link href="/cc-crm2/assets/demo/default/base/style.bundle.css?1s" rel="stylesheet" type="text/css" />
    <!--end::Base Styles -->
    <link href="/resources/css/datatables.css?986" rel="stylesheet" type="text/css" />
    <link href="/resources/css/wickedpicker.css" rel="stylesheet" type="text/css"/>
    <link rel="shortcut icon" href="/cc-crm2/assets/demo/default/media/img/logo/favicon.ico" />
</head>
<body style="text-align: center;background: #f1f1f1;padding: 0;margin:0;">
<div style="width: 100%;max-width: 1200px;margin: 0 auto;background: white;padding: 10px;">

    <div style="text-align: left;width: 100%;padding: 0px;">

        <div class="row">
            <!--begin::Portlet-->
            <form class="m-form m-form--fit m-form--label-align-right" method="post" id="fform" action="" style="width: 100%;">
                <?php if($success):?>
                    <div class="form-group m-form__group row">
                        <div class="form-success">
                            <?=$success;?>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="m-portlet__body" style="padding-top: 20px;">
                        <?php if($error):?>
                            <div class="form-group m-form__group row">
                                <div class="form-error">
                                    <?=$error;?>
                                </div>
                            </div>
                        <?php endif;?>

                        <div class="form-group m-form__group row">
                            <div class="col-12">
                                <h2>Faktureringsoplysninger</h2>
                                <hr/>
                            </div>
                        </div>

                        <div class="form-group m-form__group row">
                            <div class="col-6">
                                <div class="row">
                                    <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("Firstname");?></label>
                                    <div class="col-12">
                                        <input type="text" class="form-control" name="firstname" value="<?=$this->request->get("firstname");?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row">
                                    <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("Lastname");?></label>
                                    <div class="col-12">
                                        <input type="text" class="form-control" name="lastname" value="<?=$this->request->get("lastname");?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("Phone");?></label>
                            <div class="col-12">
                                <input type="text" class="form-control" name="phone" value="<?=$this->request->get("phone");?>"/>
                            </div>
                        </div>

                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("City");?></label>
                            <div class="col-12">
                                <input type="text" class="form-control" name="city" value="<?=$this->request->get("city");?>"/>
                            </div>
                        </div>

                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("Email");?></label>
                            <div class="col-12">
                                <input type="text" class="form-control" name="email" value="<?=$this->request->get("email");?>"/>
                            </div>
                        </div>

                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("DeliveryCompany", "Delivery company");?></label>
                            <div class="col-12">
                                <span style="width: 25px;float: left;padding-top: 4px;"><input type="radio" class="form-control" name="deliverer" value="gls" <?=((int)$this->request->get("deliverer") !== 'dao' ? 'checked="checked"': '');?>/></span> <span style="float: left;">GLS PakkeShop (gratis)</span><br/>
                                <span style="width: 25px;float: left;padding-top: 4px;"><input type="radio" class="form-control" name="deliverer" value="dao" <?=((int)$this->request->get("deliverer") == 'dao' ? 'checked="checked"': '');?>/></span> <span style="float: left;">DAO Direkte (gratis)</span>
                            </div>
                        </div>

                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("PostalCode", "Postal Code");?></label>
                            <div class="col-3">
                                <input title="text" id="postcode" class="form-control" name="postcode" value="<?=$this->request->get("postcode");?>"/>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="find" value="1" onclick="getPoints();"><?=$this->lang->get("Find");?></button>
                            </div>
                        </div>

                        <div class="form-group m-form__group row" style="display: none;" id="droppoints">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("DeliveryCompany", "Delivery company");?></label>
                            <div class="col-6" id="droppointsbody"></div>
                        </div>

                        <input type="hidden" id="droppointvalue" name="droppointvalue" value=""/>
                        <input type="hidden" name="quantity" value="<?=$quantity;?>"/>



                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("Subtotal");?></label>
                            <div class="col-12" style="color: #7f8795;font-size: 22px;font-weight: 400;">
                                <?=$data->amount;?> DKK
                            </div>
                        </div>

                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("DeliveryFee", "Delivery fee");?></label>
                            <div class="col-12" style="color: #7f8795;font-size: 22px;font-weight: 400;">
                                39 DKK
                            </div>
                        </div>


                        <div class="form-group m-form__group row">
                            <label for="example-text-input" class="col-12 col-form-label" style="text-align: left;font-weight: 600;"><?=$this->lang->get("Total");?></label>
                            <div class="col-12" style="color: #0a1461;font-size: 22px;font-weight: 400;">
                                <?=($data->amount+39);?> DKK
                            </div>
                        </div>


                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions">
                            <div class="row">
                                <div class="col-7">
                                    <button onclick="nextStep()" type="button" class="btn btn-accent m-btn m-btn--air m-btn--custom" name="save" value="1" ><?=$this->lang->get("Save");?></button>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
            </form>
            <!--end::Portlet-->
        </div>


        <form id="payform" method="post" action="https://securedt.dibspayment.com/verify/bin/90247590/index" style="display: block;">
            <input type="hidden" name="billingAddress" value="Unknown Street"/>
            <input type="hidden" name="billingCity" value="Copenhagen"/>
            <input type="hidden" name="billingCountry" value="Denmark"/>
            <input type="hidden" name="billingFirstName" value="Test"/>
            <input type="hidden" name="billingLastName" value="User"/>
            <input type="hidden" name="currency" value="DKK"/>
            <input type="hidden" name="data" value="1:T-shirt:2:1495:2:Baseball cap:1:995:"/>
            <input type="hidden" name="eMail" value="seniorshahmar@gmail.com"/>
            <input type="hidden" name="MAC" value="seniorshahmar@gmail.com"/>
            <input type="hidden" name="pageSet" value="standard"/>

            <input type="submit" name="submit" value="1">
        </form>
    </div>
</div>


<div id="dibs-complete-checkout"> </div>  


<style>
    #dibs-complete-checkout{
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: white;
    }
</style>

<script src="/cc-crm2/assets/vendors/base/vendors.bundle.js?s" type="text/javascript"></script>
<script src="/cc-crm2/assets/demo/default/base/scripts.bundle.js" type="text/javascript"></script>
<script src="/resources/js/dashboard.js?9876" type="text/javascript"></script>
<script src="/resources/js/wickedpicker.js" type="text/javascript"></script>
<script src="https://test.checkout.dibspayment.eu/v1/checkout.js?v=1" type="text/javascript"></script>

<script>
    var droppoints = {};
    function getPoints(){
        var deliverer = $("input[name='deliverer']:checked"). val();
        var postcode = document.getElementById("postcode").value;
        $.ajax({
            url: '/product/droppoints',
            type: 'POST',
            data: {
                postcode: postcode,
                deliverer: deliverer,
            },
            success: function(response){
                response = JSON.parse(response);
                if(response.status == 'error'){
                    var html = '<font style="color: red">'+response.description+'</font>';
                    document.getElementById("droppointsbody").innerHTML = html;
                    document.getElementById("droppoints").style.display = 'block';
                }else if(response.status == 'success'){
                    var html = '';
                    html += '<select class="form-control" id="droppointselect" name="droppoint" onchange="setDroppoint(this.value)">';
                    for(var i=0;i<response.data.length;i++){
                        var option = response.data[i];
                        html += '<option value="'+option.id+'" '+(option.id == 0 ? 'selected="selected"': '')+'>';
                        html += option.name+', '+option.address+(option.address2 ? ', '+option.address2: '')+', '+option.city;
                        html += '</option>';

                        droppoints[option.id] = option;
                    }
                    html += '</select>';
                    document.getElementById("droppoints").style.display = 'block';
                    document.getElementById("droppointsbody").innerHTML = html;
                }
            },
        });
    }


    function setDroppoint(value){
        document.getElementById("droppointvalue").value = JSON.stringify(droppoints[value]);
    }


    function nextStep(){
        //var droppoint = document.getElementById("droppointselect").value;
        //var deliverer = $("input[name='deliverer']:checked"). val();

        var data = $("#fform").serializeArray();
        $.ajax({
            url: '/product/pay',
            type: 'POST',
            data: data,
            success: function(response){
                response = JSON.parse(response);
                if(response.status == 'success'){
                    var paymentId = response.payment_id;
                    initCheckout(paymentId);
                }else if(response.status == 'error'){
                    alert(response.description);
                }
            }
        });

    }


    function initCheckout(paymentId){
        document.getElementById("dibs-complete-checkout").style.display = 'block';
        var checkoutOptions = {
            checkoutKey: "<?=DIBS_CHECKOUT_KEY;?>", //[Required] Test or Live GUID with dashes

            paymentId : paymentId, //[required] GUID without dashes
            containerId : "dibs-complete-checkout", //[optional] defaultValue: dibs-checkout-content
            language: "en-GB",  //language: "da-DK"
        };
        var checkout = new Dibs.Checkout(checkoutOptions);

        //this is the event that the merchant should listen to redirect to the “payment-is-ok” page

        checkout.on('payment-completed', function(response) {
            window.location = '/PaymentSuccessful';
        });
    }
</script>




</body>
</html>